// ============================================================
// contracts.js — 开局真实合同表（现役全联盟精确合同，2026-08 更新）
// 单位：年薪 = 万；years = 2026-27 赛季开局时的剩余合同年数（含当季）
// 数据源：Spotrac 2026-27 cap 表 / 合同总表 / 2023-2025 选秀合同页
//   （首发+主要轮换约 325 人精确收录；其余由 SPOTRAC_SALARIES 与估算逻辑兜底）
// 字段：years 剩余年数 / salary 当季年薪(万) / type 合同类型 / playerOption 是否带球员选项
// 类型：max 顶薪 / veteran 老将合同 / rookie 新秀合同
// ============================================================

var REAL_CONTRACTS = {

  'AJ Green': { years: 4, salary: 1004, type: 'veteran' },
  'AJ Johnson': { years: 2, salary: 324, type: 'rookie' },
  'Aaron Gordon': { years: 3, salary: 3198, type: 'veteran', playerOption: true },
  'Aaron Nesmith': { years: 1, salary: 1100, type: 'veteran' },
  'Aaron Wiggins': { years: 3, salary: 903, type: 'veteran' },
  'Ace Bailey': { years: 3, salary: 952, type: 'rookie' },
  'Adem Bona': { years: 2, salary: 230, type: 'rookie' },
  'Adou Thiero': { years: 2, salary: 215, type: 'rookie' },
  'Al Horford': { years: 2, salary: 682, type: 'veteran', playerOption: true },
  'Alex Caruso': { years: 1, salary: 1955, type: 'veteran' },
  'Alex Sarr': { years: 2, salary: 1237, type: 'rookie' },
  'Alperen Sengun': { years: 4, salary: 2900, type: 'max' },
  'Amari Williams': { years: 1, salary: 68, type: 'veteran' },
  'Amen Thompson': { years: 1, salary: 1226, type: 'rookie' },
  'Andre Drummond': { years: 1, salary: 245, type: 'veteran' },
  'Andre Jackson Jr.': { years: 1, salary: 245, type: 'rookie' },
  'Andrew Nembhard': { years: 2, salary: 1955, type: 'veteran' },
  'Andrew Wiggins': { years: 3, salary: 3017, type: 'veteran', playerOption: true },
  'Anfernee Simons': { years: 2, salary: 600, type: 'veteran', playerOption: true },
  'Anthony Black': { years: 1, salary: 1011, type: 'rookie' },
  'Anthony Davis': { years: 2, salary: 5500, type: 'max', playerOption: true },
  'Anthony Edwards': { years: 4, salary: 5000, type: 'max' },
  'Antonio Reeves': { years: 1, salary: 219, type: 'rookie' },
  'Ariel Hukporti': { years: 1, salary: 340, type: 'veteran' },
  'Asa Newell': { years: 3, salary: 340, type: 'rookie' },
  'Ausar Thompson': { years: 1, salary: 1112, type: 'rookie' },
  'Austin Reaves': { years: 4, salary: 4124, type: 'max', playerOption: true },
  'Ayo Dosunmu': { years: 5, salary: 1931, type: 'veteran', playerOption: true },
  'Bam Adebayo': { years: 3, salary: 4949, type: 'max', playerOption: true },
  'Baylor Scheierman': { years: 2, salary: 274, type: 'rookie' },
  'Ben Saraf': { years: 3, salary: 303, type: 'rookie' },
  'Ben Sheppard': { years: 1, salary: 503, type: 'rookie' },
  'Bennedict Mathurin': { years: 1, salary: 2756, type: 'veteran' },
  'Bilal Coulibaly': { years: 1, salary: 924, type: 'rookie' },
  'Bismack Biyombo': { years: 1, salary: 245, type: 'veteran' },
  'Bobby Portis': { years: 2, salary: 1452, type: 'veteran', playerOption: true },
  'Branden Carlson': { years: 1, salary: 245, type: 'veteran' },
  'Brandin Podziemski': { years: 1, salary: 568, type: 'rookie' },
  'Brandon Ingram': { years: 2, salary: 3800, type: 'veteran' },
  'Brandon Miller': { years: 1, salary: 1510, type: 'rookie' },
  'Brice Sensabaugh': { years: 1, salary: 486, type: 'rookie' },
  'Bronny James': { years: 2, salary: 230, type: 'rookie' },
  'Brook Lopez': { years: 1, salary: 919, type: 'veteran' },
  'Bub Carrington': { years: 2, salary: 490, type: 'rookie' },
  'Buddy Hield': { years: 2, salary: 966, type: 'veteran', playerOption: true },
  'Cade Cunningham': { years: 4, salary: 3700, type: 'max' },
  'Caleb Martin': { years: 2, salary: 1000, type: 'veteran', playerOption: true },
  'Cam Whitmore': { years: 1, salary: 546, type: 'rookie' },
  'Cameron Johnson': { years: 1, salary: 2306, type: 'veteran' },
  'Caris LeVert': { years: 1, salary: 1481, type: 'veteran' },
  'Carter Bryant': { years: 3, salary: 515, type: 'rookie' },
  'Cason Wallace': { years: 1, salary: 742, type: 'rookie' },
  'Cedric Coward': { years: 3, salary: 600, type: 'rookie' },
  'Charles Bassey': { years: 1, salary: 245, type: 'veteran' },
  'Chaz Lanier': { years: 3, salary: 215, type: 'rookie' },
  'Chet Holmgren': { years: 4, salary: 3000, type: 'max' },
  'Christian Braun': { years: 5, salary: 2155, type: 'veteran' },
  'Christian Koloko': { years: 1, salary: 263, type: 'veteran' },
  'Clint Capela': { years: 2, salary: 704, type: 'veteran' },
  'Coby White': { years: 3, salary: 2681, type: 'veteran' },
  'Cody Williams': { years: 2, salary: 602, type: 'rookie' },
  'Collin Gillespie': { years: 4, salary: 1071, type: 'veteran' },
  'Collin Murray-Boyles': { years: 3, salary: 665, type: 'rookie' },
  'Collin Sexton': { years: 2, salary: 937, type: 'veteran', playerOption: true },
  'Cooper Flagg': { years: 3, salary: 1470, type: 'rookie', note: '2025 状元 4 年新秀合同第 2 年' },
  'Corey Kispert': { years: 3, salary: 1398, type: 'veteran' },
  'DaRon Holmes II': { years: 2, salary: 337, type: 'rookie' },
  'Dalton Knecht': { years: 2, salary: 420, type: 'rookie' },
  'Damian Lillard': { years: 3, salary: 3592, type: 'veteran', playerOption: true },
  'Daniel Gafford': { years: 3, salary: 1726, type: 'veteran' },
  'Danny Wolf': { years: 3, salary: 294, type: 'rookie' },
  'Darius Garland': { years: 3, salary: 3300, type: 'veteran' },
  'Day’Ron Sharpe': { years: 2, salary: 1000, type: 'veteran' },
  'DeAndre Jordan': { years: 2, salary: 388, type: 'veteran' },
  'Dean Wade': { years: 4, salary: 900, type: 'veteran' },
  'Deandre Ayton': { years: 1, salary: 810, type: 'veteran' },
  'Dejounte Murray': { years: 2, salary: 3200, type: 'veteran' },
  'Deni Avdija': { years: 2, salary: 1312, type: 'veteran' },
  'Dereck Lively II': { years: 1, salary: 724, type: 'rookie' },
  'Derik Queen': { years: 3, salary: 542, type: 'rookie' },
  'Derrick Jones Jr.': { years: 1, salary: 1048, type: 'veteran' },
  'Derrick White': { years: 2, salary: 3000, type: 'veteran' },
  'Desmond Bane': { years: 3, salary: 3300, type: 'veteran' },
  'Devin Booker': { years: 2, salary: 5400, type: 'max', playerOption: true },
  'Devin Carter': { years: 2, salary: 516, type: 'rookie' },
  'Devin Vassell': { years: 3, salary: 2750, type: 'veteran' },
  'De’Aaron Fox': { years: 4, salary: 4949, type: 'max' },
  'De’Andre Hunter': { years: 1, salary: 2491, type: 'veteran' },
  'De’Anthony Melton': { years: 2, salary: 606, type: 'veteran', playerOption: true },
  'Dillon Brooks': { years: 4, salary: 2099, type: 'veteran' },
  'Dillon Jones': { years: 2, salary: 245, type: 'rookie' },
  'Domantas Sabonis': { years: 1, salary: 4900, type: 'veteran' },
  'Donovan Clingan': { years: 2, salary: 752, type: 'rookie' },
  'Donovan Mitchell': { years: 2, salary: 5000, type: 'max' },
  'Donte DiVincenzo': { years: 1, salary: 1254, type: 'veteran' },
  'Dorian Finney-Smith': { years: 3, salary: 1420, type: 'veteran', playerOption: true },
  'Drake Powell': { years: 3, salary: 354, type: 'rookie' },
  'Draymond Green': { years: 1, salary: 2768, type: 'veteran' },
  'Drew Eubanks': { years: 1, salary: 245, type: 'veteran' },
  'Duncan Robinson': { years: 2, salary: 1599, type: 'veteran' },
  'Dwight Powell': { years: 1, salary: 760, type: 'veteran' },
  'Dylan Harper': { years: 3, salary: 1299, type: 'rookie' },
  'Dyson Daniels': { years: 4, salary: 2500, type: 'veteran' },
  'Egor Demin': { years: 3, salary: 723, type: 'rookie' },
  'Evan Mobley': { years: 4, salary: 3000, type: 'max' },
  'Franz Wagner': { years: 4, salary: 3200, type: 'max' },
  'Fred VanVleet': { years: 2, salary: 3800, type: 'veteran' },
  'Gabe Vincent': { years: 1, salary: 2185, type: 'veteran' },
  'Gary Trent Jr.': { years: 4, salary: 1520, type: 'veteran' },
  'Giannis Antetokounmpo': { years: 2, salary: 5800, type: 'max', playerOption: true },
  'Goga Bitadze': { years: 1, salary: 761, type: 'veteran' },
  'Gradey Dick': { years: 1, salary: 713, type: 'rookie' },
  'Grant Williams': { years: 1, salary: 1427, type: 'veteran' },
  'Grayson Allen': { years: 2, salary: 1812, type: 'veteran', playerOption: true },
  'Gui Santos': { years: 3, salary: 463, type: 'veteran', playerOption: true },
  'Hugo Gonzalez': { years: 3, salary: 292, type: 'rookie' },
  'Immanuel Quickley': { years: 2, salary: 3300, type: 'veteran' },
  'Isaac Okoro': { years: 1, salary: 1181, type: 'veteran' },
  'Isaiah Collier': { years: 2, salary: 276, type: 'rookie' },
  'Isaiah Hartenstein': { years: 3, salary: 2315, type: 'veteran', playerOption: true },
  'Isaiah Jackson': { years: 2, salary: 700, type: 'veteran' },
  'Isaiah Joe': { years: 2, salary: 1132, type: 'veteran' },
  'Isaiah Stewart': { years: 2, salary: 1500, type: 'veteran' },
  'Ivica Zubac': { years: 2, salary: 2034, type: 'veteran' },
  'Ja Morant': { years: 2, salary: 4000, type: 'max' },
  'Jabari Smith Jr.': { years: 5, salary: 2364, type: 'veteran' },
  'Jaden McDaniels': { years: 3, salary: 2620, type: 'veteran' },
  'Jaime Jaquez Jr.': { years: 1, salary: 594, type: 'rookie' },
  'Jakob Poeltl': { years: 1, salary: 1950, type: 'veteran' },
  'Jalen Brunson': { years: 2, salary: 3400, type: 'veteran', playerOption: true },
  'Jalen Green': { years: 3, salary: 3400, type: 'veteran' },
  'Jalen Johnson': { years: 4, salary: 2900, type: 'max' },
  'Jalen Pickett': { years: 1, salary: 245, type: 'rookie' },
  'Jalen Smith': { years: 1, salary: 943, type: 'veteran' },
  'Jalen Suggs': { years: 4, salary: 3240, type: 'veteran' },
  'Jalen Williams': { years: 4, salary: 3000, type: 'max' },
  'Jamal Murray': { years: 3, salary: 5011, type: 'max' },
  'Jamal Shead': { years: 1, salary: 230, type: 'rookie' },
  'Jarace Walker': { years: 1, salary: 848, type: 'rookie' },
  'Jared McCain': { years: 2, salary: 442, type: 'rookie' },
  'Jaren Jackson Jr.': { years: 4, salary: 4900, type: 'max', playerOption: true },
  'Jarred Vanderbilt': { years: 2, salary: 1243, type: 'veteran', playerOption: true },
  'Jarrett Allen': { years: 3, salary: 2800, type: 'veteran' },
  'Jase Richardson': { years: 3, salary: 313, type: 'rookie' },
  'Jaxson Hayes': { years: 2, salary: 600, type: 'veteran' },
  'Jay Huff': { years: 2, salary: 267, type: 'veteran' },
  'Jaylen Brown': { years: 3, salary: 5300, type: 'max' },
  'Jaylen Wells': { years: 2, salary: 230, type: 'rookie' },
  'Jaylin Williams': { years: 2, salary: 777, type: 'veteran' },
  'Jaylon Tyson': { years: 2, salary: 366, type: 'rookie' },
  'Jayson Tatum': { years: 3, salary: 5400, type: 'max', playerOption: true },
  'Ja’Kobe Walter': { years: 2, salary: 381, type: 'rookie' },
  'Jerami Grant': { years: 2, salary: 3421, type: 'veteran', playerOption: true },
  'Jeremiah Fears': { years: 3, salary: 790, type: 'rookie' },
  'Jericho Sims': { years: 1, salary: 280, type: 'veteran' },
  'Jimmy Butler': { years: 1, salary: 4800, type: 'max' },
  'Joan Beringer': { years: 3, salary: 441, type: 'rookie' },
  'Jock Landale': { years: 1, salary: 1410, type: 'veteran' },
  'Joel Embiid': { years: 3, salary: 6000, type: 'max', playerOption: true },
  'John Collins': { years: 3, salary: 1700, type: 'veteran' },
  'Johni Broome': { years: 3, salary: 215, type: 'rookie' },
  'Johnny Furphy': { years: 2, salary: 230, type: 'rookie' },
  'Jordan Goodwin': { years: 4, salary: 586, type: 'veteran', playerOption: true },
  'Jordan Hawkins': { years: 1, salary: 702, type: 'rookie' },
  'Jordan Miller': { years: 3, salary: 530, type: 'veteran' },
  'Jordan Poole': { years: 1, salary: 3404, type: 'veteran' },
  'Jordan Walsh': { years: 1, salary: 241, type: 'rookie' },
  'Jose Alvarado': { years: 3, salary: 444, type: 'veteran' },
  'Josh Giddey': { years: 3, salary: 2500, type: 'veteran' },
  'Josh Green': { years: 1, salary: 1468, type: 'veteran' },
  'Josh Hart': { years: 2, salary: 2092, type: 'veteran' },
  'Josh Okogie': { years: 2, salary: 600, type: 'veteran' },
  'Jrue Holiday': { years: 1, salary: 3000, type: 'veteran' },
  'Julian Champagnie': { years: 3, salary: 1535, type: 'veteran' },
  'Julian Strawther': { years: 1, salary: 483, type: 'rookie' },
  'Julius Randle': { years: 2, salary: 3333, type: 'veteran', playerOption: true },
  'Jusuf Nurkic': { years: 2, salary: 1146, type: 'veteran' },
  'Kam Jones': { years: 3, salary: 108, type: 'rookie' },
  'Karl-Anthony Towns': { years: 2, salary: 5708, type: 'max', playerOption: true },
  'Kasparas Jakucionis': { years: 3, salary: 384, type: 'rookie' },
  'Kawhi Leonard': { years: 1, salary: 5000, type: 'max' },
  'Keegan Murray': { years: 5, salary: 2414, type: 'veteran' },
  'Keldon Johnson': { years: 1, salary: 1800, type: 'veteran' },
  'Kelly Olynyk': { years: 1, salary: 2555, type: 'veteran' },
  'Kelly Oubre Jr.': { years: 2, salary: 805, type: 'veteran' },
  'Kel’el Ware': { years: 2, salary: 465, type: 'rookie' },
  'Keon Ellis': { years: 2, salary: 900, type: 'veteran', playerOption: true },
  'Kevin Durant': { years: 1, salary: 5500, type: 'max' },
  'Kevin Huerter': { years: 3, salary: 951, type: 'veteran' },
  'Kevin Love': { years: 1, salary: 788, type: 'veteran' },
  'Kevon Looney': { years: 1, salary: 245, type: 'veteran' },
  'Keyonte George': { years: 1, salary: 656, type: 'rookie' },
  'Khaman Maluach': { years: 3, salary: 632, type: 'rookie' },
  'Khris Middleton': { years: 3, salary: 559, type: 'veteran' },
  'Klay Thompson': { years: 1, salary: 1746, type: 'veteran' },
  'Kobe Sanders': { years: 1, salary: 262, type: 'rookie' },
  'Kon Knueppel': { years: 3, salary: 1052, type: 'rookie' },
  'Kris Murray': { years: 1, salary: 532, type: 'rookie' },
  'Kristaps Porzingis': { years: 2, salary: 2000, type: 'veteran', playerOption: true },
  'KyShawn George': { years: 2, salary: 311, type: 'rookie' },
  'Kyle Filipowski': { years: 2, salary: 300, type: 'rookie' },
  'Kyle Kuzma': { years: 1, salary: 2049, type: 'veteran' },
  'Kyrie Irving': { years: 2, salary: 3949, type: 'veteran', playerOption: true },
  'LaMelo Ball': { years: 2, salary: 3600, type: 'max', playerOption: true },
  'Landry Shamet': { years: 4, salary: 549, type: 'veteran', playerOption: true },
  'Lauri Markkanen': { years: 1, salary: 4611, type: 'veteran' },
  'Leonard Miller': { years: 1, salary: 241, type: 'rookie' },
  'Liam McNeeley': { years: 3, salary: 290, type: 'rookie' },
  'Luguentz Dort': { years: 1, salary: 1772, type: 'veteran' },
  'Luka Doncic': { years: 3, salary: 4950, type: 'max', playerOption: true, note: '2028-29 球员选项' },
  'Luka Garza': { years: 1, salary: 280, type: 'veteran' },
  'Luke Kennard': { years: 2, salary: 606, type: 'veteran', playerOption: true },
  'Luke Kornet': { years: 3, salary: 1045, type: 'veteran' },
  'Malik Monk': { years: 2, salary: 2019, type: 'veteran', playerOption: true },
  'Marcus Sasser': { years: 1, salary: 520, type: 'rookie' },
  'Marcus Smart': { years: 2, salary: 606, type: 'veteran', playerOption: true },
  'Mark Williams': { years: 3, salary: 1173, type: 'veteran' },
  'Mason Plumlee': { years: 1, salary: 245, type: 'veteran' },
  'Matas Buzelis': { years: 2, salary: 572, type: 'rookie' },
  'Max Christie': { years: 2, salary: 829, type: 'veteran', playerOption: true },
  'Max Strus': { years: 1, salary: 1666, type: 'veteran' },
  'Maxime Raynaud': { years: 2, salary: 215, type: 'rookie' },
  'Micah Peavy': { years: 3, salary: 215, type: 'rookie' },
  'Michael Porter Jr.': { years: 1, salary: 4081, type: 'veteran' },
  'Mikal Bridges': { years: 2, salary: 3000, type: 'veteran' },
  'Miles Bridges': { years: 1, salary: 2283, type: 'veteran' },
  'Mitchell Robinson': { years: 3, salary: 1504, type: 'veteran', playerOption: true },
  'Moritz Wagner': { years: 2, salary: 900, type: 'veteran' },
  'Moses Moody': { years: 2, salary: 1250, type: 'veteran' },
  'Mouhamed Gueye': { years: 1, salary: 241, type: 'rookie' },
  'Myles Turner': { years: 3, salary: 2658, type: 'veteran', playerOption: true },
  'Naji Marshall': { years: 1, salary: 943, type: 'veteran' },
  'Naz Reid': { years: 4, salary: 2328, type: 'veteran', playerOption: true },
  'Neemias Queta': { years: 1, salary: 267, type: 'veteran' },
  'Nickeil Alexander-Walker': { years: 3, salary: 1440, type: 'veteran', playerOption: true },
  'Nikola Jokic': { years: 2, salary: 5900, type: 'max', playerOption: true, note: '2027-28 球员选项' },
  'Nikola Jovic': { years: 4, salary: 1620, type: 'veteran' },
  'Nikola Topic': { years: 2, salary: 543, type: 'rookie' },
  'Nikola Vucevic': { years: 1, salary: 2500, type: 'veteran' },
  'Nique Clifford': { years: 3, salary: 326, type: 'rookie' },
  'Noa Essengue': { years: 3, salary: 570, type: 'rookie' },
  'Noah Clowney': { years: 1, salary: 541, type: 'rookie' },
  'Noah Penda': { years: 3, salary: 215, type: 'rookie' },
  'Nolan Traore': { years: 3, salary: 400, type: 'rookie' },
  'Norman Powell': { years: 2, salary: 2150, type: 'veteran' },
  'OG Anunoby': { years: 3, salary: 4250, type: 'veteran', playerOption: true },
  'Obi Toppin': { years: 2, salary: 1500, type: 'veteran' },
  'Olivier-Maxence Prosper': { years: 1, salary: 250, type: 'rookie' },
  'Onyeka Okongwu': { years: 2, salary: 1610, type: 'veteran' },
  'Oso Ighodaro': { years: 2, salary: 230, type: 'rookie' },
  'Ousmane Dieng': { years: 3, salary: 575, type: 'veteran' },
  'Pacome Dadiet': { years: 2, salary: 298, type: 'rookie' },
  'Paolo Banchero': { years: 4, salary: 3700, type: 'max' },
  'Pascal Siakam': { years: 2, salary: 4892, type: 'max' },
  'Patrick Williams': { years: 3, salary: 1800, type: 'veteran', playerOption: true },
  'Paul George': { years: 2, salary: 5413, type: 'max' },
  'Paul Reed': { years: 1, salary: 560, type: 'veteran' },
  'Payton Pritchard': { years: 2, salary: 777, type: 'veteran' },
  'Pelle Larsson': { years: 1, salary: 230, type: 'rookie' },
  'Quentin Grimes': { years: 4, salary: 1395, type: 'veteran', playerOption: true },
  'Quinten Post': { years: 3, salary: 900, type: 'veteran' },
  'RJ Barrett': { years: 3, salary: 3000, type: 'veteran' },
  'Rasheer Fleming': { years: 3, salary: 215, type: 'rookie' },
  'Reed Sheppard': { years: 2, salary: 1111, type: 'rookie' },
  'Rob Dillingham': { years: 2, salary: 689, type: 'rookie' },
  'Robert Williams III': { years: 3, salary: 1400, type: 'veteran' },
  'Ron Harper Jr.': { years: 4, salary: 315, type: 'veteran' },
  'Royce O’Neale': { years: 2, salary: 1088, type: 'veteran' },
  'Rudy Gobert': { years: 2, salary: 3650, type: 'veteran', playerOption: true },
  'Rui Hachimura': { years: 2, salary: 1400, type: 'veteran' },
  'Ryan Dunn': { years: 2, salary: 278, type: 'rookie' },
  'Ryan Kalkbrenner': { years: 3, salary: 241, type: 'rookie' },
  'Sam Hauser': { years: 3, salary: 1085, type: 'veteran' },
  'Sam Merrill': { years: 3, salary: 916, type: 'veteran' },
  'Sandro Mamukelashvili': { years: 4, salary: 1300, type: 'veteran', playerOption: true },
  'Santi Aldama': { years: 2, salary: 1701, type: 'veteran' },
  'Scoot Henderson': { years: 1, salary: 1359, type: 'rookie' },
  'Scottie Barnes': { years: 4, salary: 3100, type: 'max' },
  'Shaedon Sharpe': { years: 4, salary: 2009, type: 'veteran' },
  'Shai Gilgeous-Alexander': { years: 4, salary: 4800, type: 'max' },
  'Sion James': { years: 3, salary: 241, type: 'rookie' },
  'Stephen Curry': { years: 1, salary: 6260, type: 'max', note: '2026-27 为现有合同最后一年' },
  'Stephon Castle': { years: 2, salary: 1002, type: 'rookie' },
  'Steven Adams': { years: 2, salary: 1300, type: 'veteran' },
  'T.J. McConnell': { years: 1, salary: 1100, type: 'veteran' },
  'Taelon Peter': { years: 1, salary: 219, type: 'rookie' },
  'Taj Gibson': { years: 1, salary: 382, type: 'veteran' },
  'Tari Eason': { years: 5, salary: 1405, type: 'veteran', playerOption: true },
  'Taylor Hendricks': { years: 1, salary: 781, type: 'rookie' },
  'Terance Mann': { years: 2, salary: 1550, type: 'veteran' },
  'Terrence Shannon Jr.': { years: 2, salary: 280, type: 'rookie' },
  'Thomas Bryant': { years: 1, salary: 245, type: 'veteran' },
  'Thomas Sorber': { years: 3, salary: 489, type: 'rookie' },
  'Tidjane Salaun': { years: 2, salary: 824, type: 'rookie' },
  'Tobias Harris': { years: 2, salary: 1504, type: 'veteran' },
  'Toumani Camara': { years: 4, salary: 1808, type: 'veteran' },
  'Trae Young': { years: 2, salary: 4200, type: 'max' },
  'Trayce Jackson-Davis': { years: 1, salary: 241, type: 'rookie' },
  'Tre Johnson': { years: 3, salary: 865, type: 'rookie' },
  'Trey Murphy III': { years: 3, salary: 2700, type: 'veteran' },
  'Tristan Vukcevic': { years: 2, salary: 300, type: 'veteran' },
  'Tristan da Silva': { years: 2, salary: 399, type: 'rookie' },
  'Ty Jerome': { years: 2, salary: 922, type: 'veteran', playerOption: true },
  'Tyler Herro': { years: 1, salary: 3300, type: 'veteran' },
  'Tyler Kolek': { years: 2, salary: 230, type: 'rookie' },
  'Tyrese Haliburton': { years: 3, salary: 4500, type: 'max' },
  'Tyrese Maxey': { years: 3, salary: 3800, type: 'max' },
  'Tyrese Proctor': { years: 3, salary: 215, type: 'rookie' },
  'VJ Edgecombe': { years: 3, salary: 1166, type: 'rookie' },
  'Victor Wembanyama': { years: 6, salary: 1400, type: 'max', playerOption: true, note: '新秀末季+5年2.52亿顶薪(2027-28起,末年PO)' },
  'Walker Kessler': { years: 4, salary: 3011, type: 'veteran', playerOption: true },
  'Walter Clayton Jr.': { years: 3, salary: 419, type: 'rookie' },
  'Wendell Carter Jr.': { years: 3, salary: 1810, type: 'veteran' },
  'Will Richard': { years: 3, salary: 215, type: 'rookie' },
  'Will Riley': { years: 3, salary: 369, type: 'rookie' },
  'Xavier Tillman': { years: 1, salary: 245, type: 'veteran' },
  'Yang Hansen': { years: 3, salary: 464, type: 'rookie' },
  'Yanic Konan Niederhauser': { years: 3, salary: 288, type: 'rookie' },
  'Yves Missi': { years: 2, salary: 351, type: 'rookie' },
  'Zaccharie Risacher': { years: 2, salary: 1383, type: 'rookie' },
  'Zach Collins': { years: 2, salary: 850, type: 'veteran' },
  'Zach Edey': { years: 2, salary: 633, type: 'rookie' },
  'Zach LaVine': { years: 2, salary: 4500, type: 'veteran' },
  'Zeke Nnaji': { years: 2, salary: 747, type: 'veteran', playerOption: true },
  'Zion Williamson': { years: 1, salary: 3600, type: 'veteran' },
  'C.J. McCollum': { years: 1, salary: 2100, type: 'veteran' },
  'Kingston Flemings': { years: 4, salary: 735, type: 'veteran' },
  'Zuby Ejiofor': { years: 4, salary: 345, type: 'veteran' },
  'Ryan Nembhard': { years: 2, salary: 215, type: 'veteran' },
  'Henri Veesaar': { years: 4, salary: 136, type: 'veteran' },
  'Jonathan Kuminga': { years: 2, salary: 3498, type: 'veteran' },
  'Tony Bradley': { years: 2, salary: 245, type: 'veteran' },
  'Trent Forrest': { years: 2, salary: 245, type: 'veteran' },
  'Wesley Matthews': { years: 2, salary: 245, type: 'veteran' },
  'Keaton Wallace': { years: 2, salary: 245, type: 'veteran' },
  'Dylan Windler': { years: 2, salary: 219, type: 'veteran' },
  'Day\'Ron Sharpe': { years: 2, salary: 1000, type: 'veteran' },
  'Mikel Brown Jr.': { years: 4, salary: 879, type: 'veteran' },
  'Josh Minott': { years: 2, salary: 450, type: 'veteran' },
  'Joshua Jefferson': { years: 4, salary: 297, type: 'veteran' },
  'Nikola Milutinov': { years: 2, salary: 317, type: 'veteran' },
  'Chris Cenac Jr.': { years: 4, salary: 299, type: 'veteran' },
  'Mike Conley': { years: 2, salary: 245, type: 'veteran' },
  'Torrey Craig': { years: 2, salary: 245, type: 'veteran' },
  'Blake Griffin': { years: 2, salary: 245, type: 'veteran' },
  'Mfiondu Kabengele': { years: 2, salary: 219, type: 'veteran' },
  'Max Shulga': { years: 2, salary: 219, type: 'veteran' },
  'Royce O\'Neale': { years: 4, salary: 1088, type: 'veteran' },
  'Tre Mann': { years: 2, salary: 800, type: 'veteran' },
  'Hannes Steinbach': { years: 4, salary: 523, type: 'veteran' },
  'Christian Anderson': { years: 4, salary: 426, type: 'veteran' },
  'Pat Connaughton': { years: 2, salary: 382, type: 'veteran' },
  'Moussa Diabate': { years: 2, salary: 246, type: 'veteran' },
  'Nicolas Claxton': { years: 4, salary: 2332, type: 'veteran' },
  'Caleb Wilson': { years: 4, salary: 1068, type: 'veteran' },
  'Tre Jones': { years: 2, salary: 800, type: 'veteran' },
  'Dailyn Swain': { years: 4, salary: 497, type: 'veteran' },
  'Mario Hezonja': { years: 2, salary: 245, type: 'veteran' },
  'Nae\'qwan Tomlin': { years: 2, salary: 241, type: 'veteran' },
  'Craig Porter Jr.': { years: 2, salary: 241, type: 'veteran' },
  'Meleek Thomas': { years: 2, salary: 136, type: 'veteran' },
  'Ricky Rubio': { years: 2, salary: 42, type: 'veteran' },
  'James Harden': { years: 2, salary: 4702, type: 'veteran' },
  'Ed Davis': { years: 2, salary: 245, type: 'veteran' },
  'Damian Jones': { years: 2, salary: 245, type: 'veteran' },
  'Raul Neto': { years: 2, salary: 245, type: 'veteran' },
  'Chuma Okeke': { years: 2, salary: 245, type: 'veteran' },
  'Rajon Rondo': { years: 2, salary: 245, type: 'veteran' },
  'Olivier Sarr': { years: 2, salary: 245, type: 'veteran' },
  'Tristan Thompson': { years: 1, salary: 245, type: 'veteran' },
  'PJ Washington': { years: 4, salary: 1981, type: 'veteran' },
  'Morez Johnson Jr.': { years: 4, salary: 675, type: 'veteran' },
  'Sergio de Larrea': { years: 4, salary: 318, type: 'veteran' },
  'Tarik Biberovic': { years: 2, salary: 300, type: 'veteran' },
  'Moussa Cisse': { years: 2, salary: 219, type: 'veteran' },
  'JaVale McGee': { years: 2, salary: 245, type: 'veteran' },
  'Nicolo Melli': { years: 2, salary: 507, type: 'veteran' },
  'Kai Jones': { years: 2, salary: 245, type: 'veteran' },
  'Theo Pinson': { years: 2, salary: 245, type: 'veteran' },
  'Brandon Williams': { years: 2, salary: 245, type: 'veteran' },
  'Greg Brown III': { years: 2, salary: 219, type: 'veteran' },
  'Moses Wright': { years: 2, salary: 219, type: 'veteran' },
  'McKinley Wright IV': { years: 2, salary: 219, type: 'veteran' },
  'Lonnie Walker IV': { years: 2, salary: 245, type: 'veteran' },
  'Spencer Jones': { years: 2, salary: 600, type: 'veteran' },
  'Tyus Jones': { years: 2, salary: 245, type: 'veteran' },
  'Marvin Bagley III': { years: 2, salary: 245, type: 'veteran' },
  'Alpha Diallo': { years: 2, salary: 136, type: 'veteran' },
  'Trevon Brazile': { years: 2, salary: 136, type: 'veteran' },
  'Jonas Valanciunas': { years: 2, salary: 200, type: 'veteran' },
  'Peyton Watson': { years: 2, salary: 1307, type: 'veteran' },
  'Bruce Brown Jr.': { years: 2, salary: 245, type: 'veteran' },
  'Vlatko Cancar': { years: 2, salary: 245, type: 'veteran' },
  'DeMarcus Cousins': { years: 2, salary: 245, type: 'veteran' },
  'Troy Daniels': { years: 2, salary: 245, type: 'veteran' },
  'Justin Holiday': { years: 2, salary: 245, type: 'veteran' },
  'Richard Jefferson': { years: 2, salary: 245, type: 'veteran' },
  'David Roddy': { years: 2, salary: 245, type: 'veteran' },
  'Markus Howard': { years: 2, salary: 219, type: 'veteran' },
  'Curtis Jones': { years: 2, salary: 219, type: 'veteran' },
  'Ron Holland II': { years: 4, salary: 907, type: 'veteran' },
  'Ebuka Okorie': { years: 4, salary: 448, type: 'veteran' },
  'Daniss Jenkins': { years: 2, salary: 400, type: 'veteran' },
  'Javonte Green': { years: 2, salary: 394, type: 'veteran' },
  'Gary Harris': { years: 2, salary: 382, type: 'veteran' },
  'Taurean Prince': { years: 2, salary: 382, type: 'veteran' },
  'Tolu Smith III': { years: 2, salary: 241, type: 'veteran' },
  'Jalen Duren': { years: 2, salary: 1945, type: 'veteran' },
  'Malik Beasley': { years: 2, salary: 720, type: 'veteran' },
  'Wendell Moore Jr.': { years: 2, salary: 245, type: 'veteran' },
  'Yaxel Lendeborg': { years: 4, salary: 610, type: 'veteran' },
  'De\'Anthony Melton': { years: 2, salary: 606, type: 'veteran', playerOption: true },
  'Gary Payton II': { years: 2, salary: 245, type: 'veteran' },
  'Matt Barnes': { years: 2, salary: 245, type: 'veteran' },
  'Nemanja Bjelica': { years: 2, salary: 245, type: 'veteran' },
  'Andrew Bogut': { years: 2, salary: 245, type: 'veteran' },
  'Seth Curry': { years: 2, salary: 245, type: 'veteran' },
  'Usman Garuba': { years: 2, salary: 245, type: 'veteran' },
  'JaMychal Green': { years: 2, salary: 245, type: 'veteran' },
  'Andre Iguodala': { years: 2, salary: 245, type: 'veteran' },
  'Jonas Jerebko': { years: 2, salary: 245, type: 'veteran' },
  'Anthony Lamb': { years: 2, salary: 245, type: 'veteran' },
  'David West': { years: 2, salary: 245, type: 'veteran' },
  'Jeenathan Williams': { years: 2, salary: 245, type: 'veteran' },
  'Nico Mannion': { years: 2, salary: 219, type: 'veteran' },
  'Taran Armstrong': { years: 2, salary: 219, type: 'veteran' },
  'Jerome Robinson': { years: 2, salary: 219, type: 'veteran' },
  'Bogdan Bogdanovic': { years: 2, salary: 245, type: 'veteran' },
  'Jae’Sean Tate': { years: 2, salary: 245, type: 'veteran' },
  'Isaiah Crawford': { years: 2, salary: 245, type: 'veteran' },
  'Bruce Thornton': { years: 2, salary: 136, type: 'veteran' },
  'Reggie Bullock': { years: 2, salary: 245, type: 'veteran' },
  'Jeff Green': { years: 2, salary: 245, type: 'veteran' },
  'Aaron Holiday': { years: 2, salary: 245, type: 'veteran' },
  'Boban Marjanovic': { years: 2, salary: 245, type: 'veteran' },
  'Jack McVeigh': { years: 2, salary: 219, type: 'veteran' },
  'Quenton Jackson': { years: 2, salary: 258, type: 'veteran' },
  'Larry Nance Jr.': { years: 2, salary: 245, type: 'veteran' },
  'James Johnson': { years: 2, salary: 245, type: 'veteran' },
  'Gabe York': { years: 2, salary: 219, type: 'veteran' },
  'Keaton Wagler': { years: 4, salary: 967, type: 'veteran' },
  'Kris Dunn': { years: 2, salary: 568, type: 'veteran' },
  'Cameron Christie': { years: 2, salary: 230, type: 'veteran' },
  'Baba Miller': { years: 4, salary: 171, type: 'veteran' },
  'Nicolas Batum': { years: 2, salary: 765, type: 'veteran' },
  'Bradley Beal': { years: 2, salary: 1938, type: 'veteran' },
  'Rodney Hood': { years: 2, salary: 245, type: 'veteran' },
  'Patty Mills': { years: 2, salary: 245, type: 'veteran' },
  'Ben Simmons': { years: 2, salary: 245, type: 'veteran' },
  'TyTy Washington Jr.': { years: 2, salary: 245, type: 'veteran' },
  'Xavier Moon': { years: 2, salary: 219, type: 'veteran' },
  'Norchad Omier': { years: 2, salary: 219, type: 'veteran' },
  'Jaden Hardy': { years: 2, salary: 600, type: 'veteran' },
  'Jake LaRavia': { years: 2, salary: 600, type: 'veteran' },
  'Cameron Carr': { years: 4, salary: 332, type: 'veteran' },
  'Matisse Thybulle': { years: 2, salary: 245, type: 'veteran' },
  'Ziaire Williams': { years: 2, salary: 245, type: 'veteran' },
  'Cameron Boozer': { years: 4, salary: 1185, type: 'veteran' },
  'D\'Angelo Russell': { years: 2, salary: 597, type: 'veteran' },
  'Karim Lopez': { years: 4, salary: 375, type: 'veteran' },
  'Scotty Pippen Jr.': { years: 2, salary: 246, type: 'veteran' },
  'Cam Spencer': { years: 2, salary: 241, type: 'veteran' },
  'G.G. Jackson': { years: 2, salary: 241, type: 'veteran' },
  'Kentavious Caldwell-Pope': { years: 2, salary: 245, type: 'veteran' },
  'Cole Anthony': { years: 2, salary: 370, type: 'veteran' },
  'Mamadi Diakite': { years: 2, salary: 46, type: 'veteran' },
  'Davion Mitchell': { years: 2, salary: 1240, type: 'veteran' },
  'Tim Hardaway Jr.': { years: 2, salary: 606, type: 'veteran' },
  'Myron Gardner': { years: 2, salary: 258, type: 'veteran' },
  'Dru Smith': { years: 2, salary: 258, type: 'veteran' },
  'Simone Fontecchio': { years: 2, salary: 245, type: 'veteran' },
  'Ryan Conwell': { years: 2, salary: 136, type: 'veteran' },
  'Alec Burks': { years: 2, salary: 246, type: 'veteran' },
  'Josh Christopher': { years: 2, salary: 245, type: 'veteran' },
  'Udonis Haslem': { years: 2, salary: 245, type: 'veteran' },
  'Keshad Johnson': { years: 2, salary: 245, type: 'veteran' },
  'Trevor Keels': { years: 2, salary: 245, type: 'veteran' },
  'Jordan Mickey': { years: 2, salary: 245, type: 'veteran' },
  'Dwyane Wade': { years: 2, salary: 245, type: 'veteran' },
  'Jahmir Young': { years: 2, salary: 245, type: 'veteran' },
  'Brayden Burries': { years: 4, salary: 642, type: 'veteran' },
  'Nate Ament': { years: 4, salary: 550, type: 'veteran' },
  'Kevin Porter Jr.': { years: 2, salary: 539, type: 'veteran' },
  'Kel\'el Ware': { years: 4, salary: 465, type: 'veteran' },
  'Ryan Rollins': { years: 2, salary: 400, type: 'veteran', playerOption: true },
  'Pete Nance': { years: 2, salary: 254, type: 'veteran' },
  'Cameron Thomas': { years: 2, salary: 84, type: 'veteran' },
  'Vasilije Micic': { years: 2, salary: 67, type: 'veteran' },
  'Thanasis Antetokounmpo': { years: 2, salary: 245, type: 'veteran' },
  'Alex Antetokounmpo': { years: 2, salary: 219, type: 'veteran' },
  'Jaylen Clark': { years: 2, salary: 309, type: 'veteran' },
  'Nah\'Shon Hyland': { years: 2, salary: 285, type: 'veteran' },
  'Trey Lyles': { years: 2, salary: 245, type: 'veteran' },
  'Evan Turner': { years: 2, salary: 2791, type: 'veteran' },
  'Aaron Brooks': { years: 2, salary: 245, type: 'veteran' },
  'Joe Ingles': { years: 2, salary: 245, type: 'veteran' },
  'Greg Monroe': { years: 2, salary: 245, type: 'veteran' },
  'Austin Rivers': { years: 2, salary: 245, type: 'veteran' },
  'Herb Jones': { years: 4, salary: 1490, type: 'veteran', playerOption: true },
  'Saddiq Bey': { years: 2, salary: 656, type: 'veteran' },
  'Bryce McGowens': { years: 2, salary: 258, type: 'veteran' },
  'Karlo Matkovic': { years: 2, salary: 230, type: 'veteran' },
  'Willy Hernangomez': { years: 2, salary: 464, type: 'veteran' },
  'Brandon Boston Jr': { years: 2, salary: 245, type: 'veteran' },
  'Elfrid Payton': { years: 2, salary: 245, type: 'veteran' },
  'Tony Snell': { years: 2, salary: 245, type: 'veteran' },
  'Gary Clark': { years: 2, salary: 219, type: 'veteran' },
  'Jared Harper': { years: 2, salary: 219, type: 'veteran' },
  'James Nunnally': { years: 2, salary: 219, type: 'veteran' },
  'Josh Oduro': { years: 2, salary: 219, type: 'veteran' },
  'Miles McBride': { years: 2, salary: 396, type: 'veteran' },
  'Mohamed Diawara': { years: 2, salary: 262, type: 'veteran' },
  'Jordan Clarkson': { years: 2, salary: 245, type: 'veteran' },
  'Petteri Koponen': { years: 2, salary: 317, type: 'veteran' },
  'Kevin McCullar Jr.': { years: 2, salary: 245, type: 'veteran' },
  'P.J. Tucker': { years: 2, salary: 245, type: 'veteran' },
  'Aday Mara': { years: 4, salary: 579, type: 'veteran' },
  'Kenrich Williams': { years: 2, salary: 500, type: 'veteran' },
  'Bennett Stirtz': { years: 4, salary: 472, type: 'veteran' },
  'Ajay Mitchell': { years: 2, salary: 285, type: 'veteran' },
  'Alex Ducas': { years: 2, salary: 219, type: 'veteran' },
  'Tristan Da Silva': { years: 2, salary: 399, type: 'veteran' },
  'Jamal Cain': { years: 2, salary: 258, type: 'veteran' },
  'Jonathan Isaac': { years: 2, salary: 800, type: 'veteran' },
  'Jevon Carter': { years: 2, salary: 245, type: 'veteran' },
  'Cory Joseph': { years: 2, salary: 245, type: 'veteran' },
  'Trevelin Queen': { years: 2, salary: 219, type: 'veteran' },
  'LeBron James': { years: 2, salary: 388, type: 'veteran', playerOption: true },
  'Labaron Philon Jr.': { years: 4, salary: 360, type: 'veteran' },
  'Dominick Barlow': { years: 2, salary: 342, type: 'veteran' },
  'Jabari Walker': { years: 2, salary: 258, type: 'veteran' },
  'Justin Edwards': { years: 2, salary: 241, type: 'veteran' },
  'MarJon Beauchamp': { years: 2, salary: 245, type: 'veteran' },
  'Kyle Lowry': { years: 2, salary: 245, type: 'veteran' },
  'Tyrese Martin': { years: 2, salary: 245, type: 'veteran' },
  'Trendon Watford': { years: 2, salary: 245, type: 'veteran' },
  'Jeff Dowtin': { years: 2, salary: 219, type: 'veteran' },
  'Jalen Hood-Schifino': { years: 2, salary: 219, type: 'veteran' },
  'Haywood Highsmith': { years: 2, salary: 302, type: 'veteran' },
  'Koa Peat': { years: 2, salary: 293, type: 'veteran' },
  'Jamaree Bouyea': { years: 2, salary: 258, type: 'veteran' },
  'Nassir Little': { years: 2, salary: 311, type: 'veteran' },
  'E.J. Liddell': { years: 2, salary: 71, type: 'veteran' },
  'Bol Bol': { years: 2, salary: 245, type: 'veteran' },
  'Amir Coffey': { years: 2, salary: 245, type: 'veteran' },
  'Damion Lee': { years: 2, salary: 245, type: 'veteran' },
  'Saben Lee': { years: 2, salary: 245, type: 'veteran' },
  'Isaiah Livers': { years: 2, salary: 245, type: 'veteran' },
  'Terrence Ross': { years: 2, salary: 245, type: 'veteran' },
  'Isaiah Thomas': { years: 2, salary: 245, type: 'veteran' },
  'Thaddeus Young': { years: 2, salary: 245, type: 'veteran' },
  'Udoka Azubuike': { years: 2, salary: 219, type: 'veteran' },
  'Gabriel Lundberg': { years: 2, salary: 219, type: 'veteran' },
  'Ishmail Wainright': { years: 2, salary: 219, type: 'veteran' },
  'Micah Potter': { years: 2, salary: 280, type: 'veteran', playerOption: true },
  'Vit Krejci': { years: 2, salary: 267, type: 'veteran' },
  'Sidy Cissoko': { years: 2, salary: 250, type: 'veteran' },
  'Didi Louzada': { years: 2, salary: 27, type: 'veteran' },
  'Rondae Hollis-Jefferson': { years: 2, salary: 245, type: 'veteran' },
  'Ben McLemore': { years: 2, salary: 245, type: 'veteran' },
  'Blake Wesley': { years: 2, salary: 245, type: 'veteran' },
  'Keljin Blevins': { years: 2, salary: 219, type: 'veteran' },
  'Ashton Hagans': { years: 2, salary: 219, type: 'veteran' },
  'TJ Leaf': { years: 2, salary: 219, type: 'veteran' },
  'De\'Andre Hunter': { years: 4, salary: 2491, type: 'rookie' },
  'Darius Acuff Jr.': { years: 4, salary: 802, type: 'veteran' },
  'Precious Achiuwa': { years: 2, salary: 548, type: 'veteran' },
  'Alex Karaban': { years: 2, salary: 295, type: 'veteran' },
  'Daeqwon Plowden': { years: 2, salary: 245, type: 'veteran' },
  'Dylan Cardwell': { years: 2, salary: 215, type: 'veteran' },
  'Emanuel Sharp': { years: 2, salary: 136, type: 'veteran' },
  'DeMar DeRozan': { years: 2, salary: 1000, type: 'veteran' },
  'Patrick Baldwin Jr.': { years: 2, salary: 245, type: 'veteran' },
  'Jae Crowder': { years: 2, salary: 245, type: 'veteran' },
  'Killian Hayes': { years: 2, salary: 245, type: 'veteran' },
  'Doug McDermott': { years: 2, salary: 245, type: 'veteran' },
  'Russell Westbrook': { years: 2, salary: 245, type: 'veteran' },
  'Jordan Ford': { years: 2, salary: 219, type: 'veteran' },
  'Mason Jones': { years: 2, salary: 219, type: 'veteran' },
  'Jordan McLaughlin': { years: 2, salary: 245, type: 'veteran' },
  'De\'Aaron Fox': { years: 4, salary: 4949, type: 'max' },
  'Harrison Barnes': { years: 2, salary: 800, type: 'veteran' },
  'Jayden Quaintance': { years: 4, salary: 390, type: 'veteran' },
  'Tarris Reed Jr.': { years: 4, salary: 308, type: 'veteran' },
  'Lindy Waters III': { years: 2, salary: 245, type: 'veteran' },
  'R.J. Barrett': { years: 4, salary: 2962, type: 'rookie' },
  'Allen Graves': { years: 4, salary: 407, type: 'veteran' },
  'Ja\'Kobe Walter': { years: 2, salary: 381, type: 'veteran' },
  'Kyle Anderson': { years: 2, salary: 245, type: 'veteran' },
  'Jamison Battle': { years: 2, salary: 230, type: 'veteran' },
  'Alijah Martin': { years: 2, salary: 219, type: 'veteran', playerOption: true },
  'Jordan Nwora': { years: 2, salary: 570, type: 'veteran' },
  'Will Barton': { years: 2, salary: 245, type: 'veteran' },
  'A.J. Lawson': { years: 2, salary: 245, type: 'veteran' },
  'Garrett Temple': { years: 2, salary: 245, type: 'veteran' },
  'Darryn Peterson': { years: 4, salary: 1320, type: 'veteran' },
  'John Konchar': { years: 2, salary: 616, type: 'veteran' },
  'Sviatoslav Mykhailiuk': { years: 2, salary: 385, type: 'veteran' },
  'Mohamed Bamba': { years: 2, salary: 351, type: 'veteran' },
  'Hayden Gray': { years: 2, salary: 219, type: 'veteran' },
  'Bez Mbeng': { years: 2, salary: 219, type: 'veteran' },
  'AJ Dybantsa': { years: 4, salary: 1475, type: 'veteran' },
  'Kyshawn George': { years: 2, salary: 311, type: 'veteran' },
  'Justin Champagnie': { years: 2, salary: 267, type: 'veteran' },
  'Ian Mahinmi': { years: 2, salary: 2318, type: 'veteran' },
  'Kendrick Nunn': { years: 2, salary: 682, type: 'veteran' },
  'Sharife Cooper': { years: 2, salary: 245, type: 'veteran' },
  'Anthony Gill': { years: 2, salary: 245, type: 'veteran' },
  'Ty Lawson': { years: 2, salary: 245, type: 'veteran' },
  'Shabazz Napier': { years: 2, salary: 245, type: 'veteran' },
  'Tomas Satoransky': { years: 2, salary: 245, type: 'veteran' },
  'Ramon Sessions': { years: 2, salary: 245, type: 'veteran' },
  'JT Thor': { years: 2, salary: 219, type: 'veteran' },
  'Johnathan Williams': { years: 2, salary: 219, type: 'veteran' },
  'Cassius Winston': { years: 2, salary: 219, type: 'veteran' },

};


// ============ 合并自 spotrac-salaries.js ============

// ============================================================
// spotrac-salaries.js - 2026-27 NBA 全联盟真实年薪/合同类型（抓取自 Spotrac cap 页，单位：万）
// 生成于 2026-08-11；s = 2026-27 年薪（四舍五入取整万）；t = 合同类型；a = 年龄
// 类型说明：RK-1ST 首轮新秀 / RK-2ND 次轮新秀 / RK-EXT 新秀续约 / VET-EXT 老将续约 /
//     DVET-EXT/DRK-EXT 顶薪续约 / FA 自由球员 / S&T 先签后换 / ROS 转正 / RK 新秀 / UD 落选 / E10 展览合同
// 数据优先级：REAL_CONTRACTS（球星精确年限）> 本表年薪；2026 届新秀走真实新秀薪资表
// ============================================================
var SPOTRAC_SALARIES = {
  'A.J. Lawson': { s: 245, t: 'ROS', a: 26 },
  'AJ Dybantsa': { s: 1475, t: 'RK-1ST', a: 20 },
  'AJ Green': { s: 1004, t: 'VET-EXT', a: 27 },
  'AJ Johnson': { s: 324, t: 'RK-1ST', a: 22 },
  'Aaron Brooks': { s: 245, t: '', a: 42 },
  'Aaron Gordon': { s: 3198, t: 'VET-EXT', a: 31 },
  'Aaron Holiday': { s: 245, t: 'FA', a: 30 },
  'Aaron Nesmith': { s: 1100, t: 'RK-EXT', a: 27 },
  'Aaron Wiggins': { s: 903, t: 'FA', a: 28 },
  'Ace Bailey': { s: 952, t: 'RK-1ST', a: 20 },
  'Aday Mara': { s: 579, t: 'RK-1ST', a: 21 },
  'Adem Bona': { s: 230, t: 'RK-2ND', a: 23 },
  'Adou Thiero': { s: 215, t: 'RK-2ND', a: 22 },
  'Ajay Mitchell': { s: 285, t: 'FA', a: 24 },
  'Al Horford': { s: 682, t: 'FA', a: 40 },
  'Alec Burks': { s: 246, t: 'FA', a: 35 },
  'Alex Antetokounmpo': { s: 219, t: '2W', a: 25 },
  'Alex Caruso': { s: 1955, t: 'VET-EXT', a: 32 },
  'Alex Ducas': { s: 219, t: '2W', a: 26 },
  'Alex Karaban': { s: 295, t: 'RK-1ST', a: 24 },
  'Alex Sarr': { s: 1237, t: 'RK-1ST', a: 21 },
  'Alijah Martin': { s: 219, t: 'FA', a: 25 },
  'Allen Graves': { s: 407, t: 'RK-1ST', a: 20 },
  'Alperen Sengun': { s: 3564, t: 'RK-EXT', a: 24 },
  'Alpha Diallo': { s: 136, t: 'UD', a: 29 },
  'Amen Thompson': { s: 1226, t: 'RK-1ST', a: 24 },
  'Amir Coffey': { s: 245, t: 'FA', a: 29 },
  'Andre Drummond': { s: 245, t: 'FA', a: 33 },
  'Andre Iguodala': { s: 245, t: 'FA', a: 43 },
  'Andre Jackson Jr.': { s: 245, t: 'RK-2ND', a: 25 },
  'Andrew Bogut': { s: 245, t: '', a: 42 },
  'Andrew Nembhard': { s: 1955, t: 'VET-EXT', a: 27 },
  'Andrew Wiggins': { s: 3017, t: 'VET-EXT', a: 31 },
  'Anfernee Simons': { s: 600, t: 'FA', a: 27 },
  'Anthony Black': { s: 1011, t: 'RK-1ST', a: 23 },
  'Anthony Davis': { s: 5846, t: 'VET-EXT', a: 33 },
  'Anthony Edwards': { s: 4892, t: 'DRK-EXT', a: 25 },
  'Anthony Gill': { s: 245, t: 'FA', a: 34 },
  'Anthony Lamb': { s: 245, t: 'ROS', a: 29 },
  'Antonio Reeves': { s: 219, t: '2W', a: 26 },
  'Ariel Hukporti': { s: 340, t: 'FA', a: 24 },
  'Asa Newell': { s: 340, t: 'RK-1ST', a: 21 },
  'Ashton Hagans': { s: 219, t: '2W', a: 27 },
  'Ausar Thompson': { s: 1112, t: 'RK-1ST', a: 24 },
  'Austin Reaves': { s: 4124, t: 'FA', a: 28 },
  'Austin Rivers': { s: 245, t: 'FA', a: 34 },
  'Ayo Dosunmu': { s: 1931, t: 'FA', a: 27 },
  'Baba Miller': { s: 171, t: 'RK-2ND', a: 22 },
  'Bam Adebayo': { s: 4949, t: 'VET-EXT', a: 29 },
  'Baylor Scheierman': { s: 274, t: 'RK-1ST', a: 26 },
  'Ben McLemore': { s: 245, t: 'FA', a: 33 },
  'Ben Saraf': { s: 303, t: 'RK-1ST', a: 20 },
  'Ben Sheppard': { s: 503, t: 'RK-1ST', a: 25 },
  'Ben Simmons': { s: 245, t: 'ROS', a: 30 },
  'Bennedict Mathurin': { s: 2756, t: 'RK-1ST', a: 24 },
  'Bennett Stirtz': { s: 472, t: 'RK-1ST', a: 23 },
  'Bez Mbeng': { s: 219, t: 'ROS', a: 24 },
  'Bilal Coulibaly': { s: 924, t: 'RK-1ST', a: 22 },
  'Bismack Biyombo': { s: 245, t: 'FA', a: 34 },
  'Blake Griffin': { s: 245, t: 'FA', a: 37 },
  'Blake Wesley': { s: 245, t: 'FA', a: 23 },
  'Boban Marjanovic': { s: 245, t: 'FA', a: 38 },
  'Bobby Portis': { s: 1452, t: 'FA', a: 31 },
  'Bogdan Bogdanovic': { s: 245, t: 'FA', a: 34 },
  'Bogoljub Marković': { s: 136, t: 'RK-2ND', a: 21 },
  'Bol Bol': { s: 245, t: 'FA', a: 27 },
  'Bradley Beal': { s: 642, t: 'FA', a: 33 },
  'Branden Carlson': { s: 245, t: 'FA', a: 27 },
  'Brandin Podziemski': { s: 568, t: 'RK-1ST', a: 23 },
  'Brandon Boston Jr': { s: 245, t: 'ROS', a: 25 },
  'Brandon Ingram': { s: 4000, t: 'VET-EXT', a: 29 },
  'Brandon Miller': { s: 1510, t: 'RK-1ST', a: 24 },
  'Brandon Williams': { s: 245, t: 'ROS', a: 27 },
  'Brayden Burries': { s: 642, t: 'RK-1ST', a: 21 },
  'Brice Sensabaugh': { s: 486, t: 'RK-1ST', a: 23 },
  'Bronny James': { s: 230, t: 'RK-2ND', a: 22 },
  'Brook Lopez': { s: 919, t: 'FA', a: 38 },
  'Bruce Brown Jr.': { s: 245, t: 'FA', a: 30 },
  'Bruce Thornton': { s: 136, t: 'RK-2ND', a: 23 },
  'Bryce McGowens': { s: 258, t: 'ROS', a: 24 },
  'Bub Carrington': { s: 490, t: 'RK-1ST', a: 21 },
  'Buddy Hield': { s: 966, t: 'S&T', a: 34 },
  'C.J. McCollum': { s: 2100, t: 'VET-EXT', a: 35 },
  'Cade Cunningham': { s: 5011, t: 'DRK-EXT', a: 25 },
  'Caleb Martin': { s: 1000, t: 'FA', a: 31 },
  'Caleb Wilson': { s: 1068, t: 'RK-1ST', a: 20 },
  'Cam Spencer': { s: 241, t: 'FA', a: 26 },
  'Cam Whitmore': { s: 546, t: 'RK-1ST', a: 22 },
  'Cameron Boozer': { s: 1185, t: 'RK-1ST', a: 19 },
  'Cameron Carr': { s: 332, t: 'RK-1ST', a: 22 },
  'Cameron Christie': { s: 230, t: 'RK-2ND', a: 21 },
  'Cameron Johnson': { s: 2306, t: 'FA', a: 30 },
  'Caris LeVert': { s: 1481, t: 'FA', a: 32 },
  'Carter Bryant': { s: 515, t: 'RK-1ST', a: 21 },
  'Cason Wallace': { s: 742, t: 'RK-1ST', a: 23 },
  'Cassius Winston': { s: 219, t: '2W', a: 28 },
  'Cedric Coward': { s: 600, t: 'RK-1ST', a: 23 },
  'Charles Bassey': { s: 245, t: 'FA', a: 26 },
  'Chaz Lanier': { s: 215, t: 'RK-2ND', a: 25 },
  'Chet Holmgren': { s: 4124, t: 'rookie-maximum-extension', a: 24 },
  'Chris Cenac Jr.': { s: 299, t: 'RK-1ST', a: 20 },
  'Christian Anderson': { s: 426, t: 'RK-1ST', a: 20 },
  'Christian Braun': { s: 2155, t: 'RK-EXT', a: 25 },
  'Chuma Okeke': { s: 245, t: 'ROS', a: 28 },
  'Clint Capela': { s: 704, t: 'S&T', a: 32 },
  'Coby White': { s: 2681, t: 'FA', a: 26 },
  'Cody Williams': { s: 602, t: 'RK-1ST', a: 22 },
  'Collin Gillespie': { s: 1071, t: 'FA', a: 27 },
  'Collin Murray-Boyles': { s: 665, t: 'RK-1ST', a: 21 },
  'Collin Sexton': { s: 937, t: 'FA', a: 28 },
  'Cooper Flagg': { s: 1452, t: 'RK-1ST', a: 20 },
  'Corey Kispert': { s: 1398, t: 'RK-EXT', a: 27 },
  'Cory Joseph': { s: 245, t: 'FA', a: 35 },
  'Craig Porter Jr.': { s: 241, t: 'ROS', a: 26 },
  'Curtis Jones': { s: 219, t: '2W', a: 25 },
  'D\'Angelo Russell': { s: 597, t: 'FA', a: 30 },
  'DaRon Holmes II': { s: 337, t: 'RK-1ST', a: 24 },
  'Daeqwon Plowden': { s: 245, t: 'FA', a: 28 },
  'Dailyn Swain': { s: 497, t: 'RK-1ST', a: 21 },
  'Dalton Knecht': { s: 420, t: 'RK-1ST', a: 25 },
  'Damian Jones': { s: 245, t: 'FA', a: 31 },
  'Damian Lillard': { s: 1340, t: 'FA', a: 36 },
  'Damion Lee': { s: 245, t: 'FA', a: 34 },
  'Daniel Gafford': { s: 1726, t: 'VET-EXT', a: 28 },
  'Daniss Jenkins': { s: 400, t: 'ROS', a: 25 },
  'Danny Wolf': { s: 294, t: 'RK-1ST', a: 22 },
  'Darius Acuff Jr.': { s: 802, t: 'RK-1ST', a: 20 },
  'Darius Garland': { s: 4217, t: 'DRK-EXT', a: 27 },
  'Darryn Peterson': { s: 1320, t: 'RK-1ST', a: 20 },
  'David Roddy': { s: 245, t: '2W', a: 25 },
  'David West': { s: 245, t: '', a: 46 },
  'Davion Mitchell': { s: 1240, t: 'FA', a: 28 },
  'Day\'Ron Sharpe': { s: 1000, t: 'FA', a: 25 },
  'De\'Aaron Fox': { s: 4949, t: 'VET-EXT', a: 29 },
  'De\'Andre Hunter': { s: 2491, t: 'RK-EXT', a: 29 },
  'De\'Anthony Melton': { s: 606, t: 'FA', a: 28 },
  'DeAndre Jordan': { s: 388, t: 'FA', a: 38 },
  'DeMarcus Cousins': { s: 245, t: 'ROS', a: 36 },
  'Dean Wade': { s: 900, t: 'FA', a: 30 },
  'Deandre Ayton': { s: 810, t: 'FA', a: 28 },
  'Dejounte Murray': { s: 3279, t: 'VET-EXT', a: 30 },
  'Deni Avdija': { s: 1312, t: 'RK-EXT', a: 26 },
  'Dennis Schröder': { s: 1481, t: 'FA', a: 33 },
  'Dereck Lively II': { s: 724, t: 'RK-1ST', a: 22 },
  'Derik Queen': { s: 542, t: 'RK-1ST', a: 22 },
  'Derrick Jones Jr.': { s: 1048, t: 'FA', a: 29 },
  'Derrick White': { s: 3035, t: 'VET-EXT', a: 32 },
  'Desmond Bane': { s: 3945, t: 'RK-EXT', a: 28 },
  'Devin Booker': { s: 5708, t: 'DVET-EXT', a: 30 },
  'Devin Carter': { s: 516, t: 'RK-1ST', a: 24 },
  'Devin Vassell': { s: 2750, t: 'RK-EXT', a: 26 },
  'Dillon Brooks': { s: 2099, t: 'S&T', a: 31 },
  'Dillon Jones': { s: 245, t: '2W', a: 25 },
  'Domantas Sabonis': { s: 4547, t: 'VET-EXT', a: 30 },
  'Dominick Barlow': { s: 342, t: 'ROS', a: 23 },
  'Donovan Clingan': { s: 752, t: 'RK-1ST', a: 22 },
  'Donovan Mitchell': { s: 5011, t: 'VET-EXT', a: 30 },
  'Donte DiVincenzo': { s: 1254, t: 'FA', a: 30 },
  'Dorian Finney-Smith': { s: 1420, t: 'FA', a: 33 },
  'Doug McDermott': { s: 245, t: 'FA', a: 35 },
  'Drake Powell': { s: 354, t: 'RK-1ST', a: 21 },
  'Draymond Green': { s: 2768, t: 'FA', a: 36 },
  'Drew Eubanks': { s: 245, t: 'FA', a: 29 },
  'Dru Smith': { s: 258, t: 'FA', a: 29 },
  'Duncan Robinson': { s: 1599, t: 'S&T', a: 32 },
  'Dwight Powell': { s: 760, t: 'FA', a: 35 },
  'Dwyane Wade': { s: 245, t: '', a: 45 },
  'Dylan Cardwell': { s: 215, t: 'ROS', a: 25 },
  'Dylan Harper': { s: 1299, t: 'RK-1ST', a: 20 },
  'Dylan Windler': { s: 219, t: '2W', a: 30 },
  'Dyson Daniels': { s: 2500, t: 'RK-EXT', a: 23 },
  'Ebuka Okorie': { s: 448, t: 'RK-1ST', a: 19 },
  'Ed Davis': { s: 245, t: '', a: 37 },
  'Egor Demin': { s: 723, t: 'RK-1ST', a: 20 },
  'Elfrid Payton': { s: 245, t: 'ROS', a: 32 },
  'Emanuel Sharp': { s: 136, t: 'RK-2ND', a: 22 },
  'Evan Mobley': { s: 5011, t: 'DRK-EXT', a: 25 },
  'Evan Turner': { s: 2791, t: '', a: 38 },
  'Franz Wagner': { s: 4175, t: 'DRK-EXT', a: 25 },
  'Fred VanVleet': { s: 2500, t: 'FA', a: 32 },
  'G.G. Jackson': { s: 241, t: 'ROS', a: 22 },
  'Gabe Vincent': { s: 2185, t: 'FA', a: 30 },
  'Gabe York': { s: 219, t: '2W', a: 33 },
  'Gabriel Lundberg': { s: 219, t: '2W', a: 32 },
  'Garrett Temple': { s: 245, t: 'FA', a: 40 },
  'Gary Clark': { s: 219, t: '2W', a: 32 },
  'Gary Harris': { s: 382, t: 'FA', a: 32 },
  'Gary Payton II': { s: 245, t: 'FA', a: 34 },
  'Gary Trent Jr.': { s: 1520, t: 'FA', a: 28 },
  'Giannis Antetokounmpo': { s: 5846, t: 'VET-EXT', a: 32 },
  'Goga Bitadze': { s: 761, t: 'FA', a: 27 },
  'Gradey Dick': { s: 713, t: 'RK-1ST', a: 23 },
  'Grant Williams': { s: 1427, t: 'S&T', a: 28 },
  'Grayson Allen': { s: 1812, t: 'VET-EXT', a: 31 },
  'Greg Brown III': { s: 219, t: '2W', a: 25 },
  'Greg Monroe': { s: 245, t: 'ROS', a: 36 },
  'Gui Santos': { s: 463, t: 'VET-EXT', a: 24 },
  'Hannes Steinbach': { s: 523, t: 'RK-1ST', a: 20 },
  'Harrison Barnes': { s: 800, t: 'FA', a: 34 },
  'Hayden Gray': { s: 219, t: 'ROS', a: 23 },
  'Haywood Highsmith': { s: 302, t: 'ROS', a: 30 },
  'Henri Veesaar': { s: 136, t: 'RK-2ND', a: 22 },
  'Herb Jones': { s: 1490, t: 'FA', a: 28 },
  'Hugo Gonzalez': { s: 292, t: 'RK-1ST', a: 20 },
  'Ian Mahinmi': { s: 2318, t: '', a: 40 },
  'Immanuel Quickley': { s: 3250, t: 'FA', a: 27 },
  'Isaac Okoro': { s: 1181, t: 'FA', a: 26 },
  'Isaiah Collier': { s: 276, t: 'RK-1ST', a: 22 },
  'Isaiah Crawford': { s: 245, t: 'FA', a: 25 },
  'Isaiah Hartenstein': { s: 2315, t: 'FA', a: 28 },
  'Isaiah Jackson': { s: 700, t: 'FA', a: 25 },
  'Isaiah Joe': { s: 1132, t: 'FA', a: 27 },
  'Isaiah Livers': { s: 245, t: '2W', a: 28 },
  'Isaiah Stewart': { s: 1500, t: 'RK-EXT', a: 25 },
  'Isaiah Thomas': { s: 245, t: 'ROS', a: 37 },
  'Ishmail Wainright': { s: 219, t: '2W', a: 32 },
  'Ivica Zubac': { s: 2034, t: 'VET-EXT', a: 29 },
  'JT Thor': { s: 219, t: '2W', a: 24 },
  'Ja Morant': { s: 4217, t: 'DRK-EXT', a: 27 },
  'Ja\'Kobe Walter': { s: 381, t: 'RK-1ST', a: 22 },
  'JaMychal Green': { s: 245, t: 'FA', a: 36 },
  'JaVale McGee': { s: 245, t: 'FA', a: 39 },
  'Jabari Smith Jr.': { s: 2364, t: 'RK-EXT', a: 23 },
  'Jabari Walker': { s: 258, t: 'ROS', a: 24 },
  'Jack McVeigh': { s: 219, t: '2W', a: 30 },
  'Jaden Hardy': { s: 600, t: 'VET-EXT', a: 24 },
  'Jaden McDaniels': { s: 2620, t: 'RK-EXT', a: 26 },
  'Jae Crowder': { s: 245, t: 'ROS', a: 36 },
  'Jae’Sean Tate': { s: 245, t: 'FA', a: 31 },
  'Jahmir Young': { s: 245, t: 'ROS', a: 26 },
  'Jaime Jaquez Jr.': { s: 594, t: 'RK-1ST', a: 25 },
  'Jake LaRavia': { s: 600, t: 'FA', a: 25 },
  'Jakob Poeltl': { s: 1950, t: 'FA', a: 31 },
  'Jalen Brunson': { s: 3774, t: 'VET-EXT', a: 30 },
  'Jalen Duren': { s: 1945, t: 'RK-1ST', a: 23 },
  'Jalen Green': { s: 3625, t: 'RK-EXT', a: 24 },
  'Jalen Hood-Schifino': { s: 219, t: '2W', a: 23 },
  'Jalen Johnson': { s: 3000, t: 'RK-EXT', a: 25 },
  'Jalen Pickett': { s: 245, t: 'RK-2ND', a: 27 },
  'Jalen Smith': { s: 943, t: 'FA', a: 26 },
  'Jalen Suggs': { s: 3240, t: 'RK-EXT', a: 25 },
  'Jalen Williams': { s: 4124, t: 'DRK-EXT', a: 25 },
  'Jamal Cain': { s: 258, t: 'ROS', a: 27 },
  'Jamal Murray': { s: 5011, t: 'VET-EXT', a: 29 },
  'Jamal Shead': { s: 230, t: 'RK-2ND', a: 24 },
  'Jamaree Bouyea': { s: 258, t: 'ROS', a: 27 },
  'James Harden': { s: 4702, t: 'FA', a: 37 },
  'James Johnson': { s: 245, t: 'FA', a: 39 },
  'James Nunnally': { s: 219, t: '2W', a: 36 },
  'Jamison Battle': { s: 230, t: 'ROS', a: 25 },
  'Jarace Walker': { s: 848, t: 'RK-1ST', a: 23 },
  'Jared Harper': { s: 219, t: '2W', a: 29 },
  'Jared McCain': { s: 442, t: 'RK-1ST', a: 22 },
  'Jaren Jackson Jr.': { s: 4900, t: 'VET-EXT', a: 27 },
  'Jarred Vanderbilt': { s: 1243, t: 'VET-EXT', a: 27 },
  'Jarrett Allen': { s: 2800, t: 'VET-EXT', a: 28 },
  'Jase Richardson': { s: 313, t: 'RK-1ST', a: 21 },
  'Javonte Green': { s: 394, t: 'FA', a: 33 },
  'Jaxson Hayes': { s: 600, t: 'FA', a: 26 },
  'Jay Huff': { s: 267, t: '', a: 28 },
  'Jayden Quaintance': { s: 390, t: 'RK-1ST', a: 19 },
  'Jaylen Brown': { s: 5774, t: 'DVET-EXT', a: 30 },
  'Jaylen Clark': { s: 309, t: 'FA', a: 25 },
  'Jaylen Wells': { s: 230, t: 'RK-2ND', a: 23 },
  'Jaylin Williams': { s: 777, t: 'VET-EXT', a: 24 },
  'Jaylon Tyson': { s: 366, t: 'RK-1ST', a: 24 },
  'Jayson Tatum': { s: 5846, t: 'DVET-EXT', a: 28 },
  'Jeenathan Williams': { s: 245, t: '2W', a: 27 },
  'Jeff Dowtin': { s: 219, t: '2W', a: 29 },
  'Jeff Green': { s: 245, t: 'FA', a: 40 },
  'Jerami Grant': { s: 3421, t: 'FA', a: 32 },
  'Jeremiah Fears': { s: 790, t: 'RK-1ST', a: 20 },
  'Jericho Sims': { s: 280, t: 'FA', a: 28 },
  'Jerome Robinson': { s: 219, t: '2W', a: 29 },
  'Jevon Carter': { s: 245, t: 'FA', a: 31 },
  'Jimmy Butler': { s: 5683, t: 'VET-EXT', a: 37 },
  'Joan Beringer': { s: 441, t: 'RK-1ST', a: 20 },
  'Jock Landale': { s: 1410, t: 'FA', a: 31 },
  'Joe Ingles': { s: 245, t: 'FA', a: 39 },
  'Joel Embiid': { s: 5799, t: 'VET-EXT', a: 32 },
  'John Collins': { s: 1700, t: 'S&T', a: 29 },
  'John Konchar': { s: 616, t: 'VET-EXT', a: 30 },
  'Johnathan Williams': { s: 219, t: '2W', a: 31 },
  'Johni Broome': { s: 215, t: 'RK-2ND', a: 24 },
  'Johnny Furphy': { s: 230, t: 'RK-2ND', a: 22 },
  'Jonas Jerebko': { s: 245, t: '', a: 39 },
  'Jonathan Isaac': { s: 245, t: 'FA', a: 29 },
  'Jonathan Kuminga': { s: 3498, t: 'FA', a: 24 },
  'Jordan Clarkson': { s: 245, t: 'FA', a: 34 },
  'Jordan Ford': { s: 219, t: '2W', a: 28 },
  'Jordan Goodwin': { s: 586, t: 'FA', a: 28 },
  'Jordan Hawkins': { s: 702, t: 'RK-1ST', a: 24 },
  'Jordan McLaughlin': { s: 245, t: 'FA', a: 30 },
  'Jordan Mickey': { s: 245, t: '', a: 32 },
  'Jordan Miller': { s: 530, t: 'FA', a: 27 },
  'Jordan Nwora': { s: 570, t: 'FA', a: 28 },
  'Jordan Poole': { s: 3404, t: 'RK-EXT', a: 27 },
  'Jordan Walsh': { s: 241, t: 'RK-2ND', a: 22 },
  'Jose Alvarado': { s: 444, t: 'FA', a: 28 },
  'Josh Christopher': { s: 245, t: '2W', a: 25 },
  'Josh Giddey': { s: 2500, t: 'FA', a: 24 },
  'Josh Green': { s: 1468, t: 'RK-EXT', a: 26 },
  'Josh Hart': { s: 2092, t: 'VET-EXT', a: 31 },
  'Josh Minott': { s: 450, t: 'FA', a: 24 },
  'Josh Oduro': { s: 219, t: '2W', a: 26 },
  'Josh Okogie': { s: 600, t: 'FA', a: 28 },
  'Joshua Jefferson': { s: 297, t: 'RK-1ST', a: 23 },
  'Jrue Holiday': { s: 3480, t: 'VET-EXT', a: 36 },
  'Julian Champagnie': { s: 1535, t: 'VET-EXT', a: 25 },
  'Julian Strawther': { s: 483, t: 'RK-1ST', a: 24 },
  'Julius Randle': { s: 3333, t: 'FA', a: 32 },
  'Justin Champagnie': { s: 267, t: 'ROS', a: 25 },
  'Justin Edwards': { s: 241, t: 'FA', a: 23 },
  'Justin Holiday': { s: 245, t: 'FA', a: 37 },
  'Jusuf Nurkic': { s: 1146, t: 'FA', a: 32 },
  'Kai Jones': { s: 245, t: '2W', a: 26 },
  'Karim Lopez': { s: 375, t: 'RK-1ST', a: 19 },
  'Karl-Anthony Towns': { s: 5708, t: 'DVET-EXT', a: 31 },
  'Karlo Matkovic': { s: 230, t: 'RK-2ND', a: 25 },
  'Kasparas Jakucionis': { s: 384, t: 'RK-1ST', a: 20 },
  'Kawhi Leonard': { s: 5030, t: 'VET-EXT', a: 35 },
  'Keaton Wagler': { s: 967, t: 'RK-1ST', a: 19 },
  'Keaton Wallace': { s: 245, t: '', a: 27 },
  'Keegan Murray': { s: 2414, t: 'RK-EXT', a: 26 },
  'Keion Brooks Jr.': { s: 219, t: '2W', a: 0 },
  'Kel\'el Ware': { s: 465, t: 'RK-1ST', a: 22 },
  'Keldon Johnson': { s: 1800, t: 'RK-EXT', a: 27 },
  'Keljin Blevins': { s: 219, t: '2W', a: 31 },
  'Kelly Olynyk': { s: 2555, t: 'VET-EXT', a: 35 },
  'Kelly Oubre Jr.': { s: 805, t: 'FA', a: 31 },
  'Kendrick Nunn': { s: 682, t: 'FA', a: 31 },
  'Kenrich Williams': { s: 500, t: 'FA', a: 32 },
  'Kentavious Caldwell-Pope': { s: 245, t: 'FA', a: 33 },
  'Keon Ellis': { s: 900, t: 'FA', a: 27 },
  'Keshad Johnson': { s: 245, t: 'ROS', a: 25 },
  'Kevin Durant': { s: 4390, t: 'VET-EXT', a: 38 },
  'Kevin Huerter': { s: 951, t: 'FA', a: 28 },
  'Kevin Love': { s: 788, t: 'FA', a: 38 },
  'Kevin McCullar Jr.': { s: 245, t: '2W', a: 25 },
  'Kevin Porter Jr.': { s: 539, t: 'FA', a: 26 },
  'Kevon Looney': { s: 245, t: 'FA', a: 30 },
  'Keyonte George': { s: 656, t: 'RK-1ST', a: 23 },
  'Khaman Maluach': { s: 632, t: 'RK-1ST', a: 20 },
  'Khris Middleton': { s: 559, t: 'S&T', a: 35 },
  'Killian Hayes': { s: 245, t: 'ROS', a: 25 },
  'Kingston Flemings': { s: 735, t: 'RK-1ST', a: 20 },
  'Klay Thompson': { s: 1746, t: 'S&T', a: 36 },
  'Koa Peat': { s: 293, t: 'RK-1ST', a: 20 },
  'Kobe Sanders': { s: 262, t: 'FA', a: 24 },
  'Kon Knueppel': { s: 1052, t: 'RK-1ST', a: 21 },
  'Kris Dunn': { s: 568, t: 'S&T', a: 32 },
  'Kris Murray': { s: 532, t: 'RK-1ST', a: 26 },
  'Kristaps Porzingis': { s: 2000, t: 'VET-EXT', a: 31 },
  'Kyle Anderson': { s: 245, t: 'FA', a: 33 },
  'Kyle Filipowski': { s: 300, t: 'RK', a: 23 },
  'Kyle Kuzma': { s: 2049, t: 'FA', a: 31 },
  'Kyle Lowry': { s: 245, t: 'FA', a: 40 },
  'Kyrie Irving': { s: 3949, t: 'FA', a: 34 },
  'Kyshawn George': { s: 311, t: 'RK-1ST', a: 23 },
  'LaMelo Ball': { s: 4077, t: 'DRK-EXT', a: 25 },
  'Labaron Philon Jr.': { s: 360, t: 'RK-1ST', a: 21 },
  'Landry Shamet': { s: 549, t: 'FA', a: 29 },
  'Larry Nance Jr.': { s: 245, t: 'FA', a: 34 },
  'Lauri Markkanen': { s: 4611, t: 'VET-EXT', a: 29 },
  'LeBron James': { s: 388, t: 'FA', a: 42 },
  'Leonard Miller': { s: 241, t: 'RK-2ND', a: 23 },
  'Liam McNeeley': { s: 290, t: 'RK-1ST', a: 21 },
  'Lindy Waters III': { s: 245, t: 'FA', a: 29 },
  'Lonnie Walker IV': { s: 245, t: 'FA', a: 28 },
  'Luguentz Dort': { s: 1772, t: 'FA', a: 27 },
  'Luka Doncic': { s: 4949, t: 'VET-EXT', a: 27 },
  'Luka Garza': { s: 280, t: 'FA', a: 28 },
  'Luke Kennard': { s: 606, t: 'FA', a: 30 },
  'Luke Kornet': { s: 1045, t: 'FA', a: 31 },
  'Malik Beasley': { s: 720, t: 'FA', a: 30 },
  'Malik Monk': { s: 2019, t: 'FA', a: 28 },
  'MarJon Beauchamp': { s: 245, t: '2W', a: 26 },
  'Marcus Sasser': { s: 520, t: 'RK-1ST', a: 26 },
  'Marcus Smart': { s: 606, t: 'FA', a: 32 },
  'Mario Hezonja': { s: 245, t: 'FA', a: 31 },
  'Mark Williams': { s: 1173, t: 'FA', a: 25 },
  'Markus Howard': { s: 219, t: '2W', a: 27 },
  'Marvin Bagley III': { s: 245, t: 'FA', a: 27 },
  'Mason Jones': { s: 219, t: '2W', a: 28 },
  'Mason Plumlee': { s: 245, t: 'ROS', a: 36 },
  'Matas Buzelis': { s: 572, t: 'RK-1ST', a: 22 },
  'Matisse Thybulle': { s: 245, t: 'FA', a: 29 },
  'Matt Barnes': { s: 245, t: '', a: 46 },
  'Max Christie': { s: 829, t: 'FA', a: 23 },
  'Max Shulga': { s: 219, t: 'ROS', a: 24 },
  'Max Strus': { s: 1666, t: 'S&T', a: 30 },
  'Maxime Raynaud': { s: 215, t: 'RK-2ND', a: 23 },
  'McKinley Wright IV': { s: 219, t: '2W', a: 28 },
  'Meleek Thomas': { s: 136, t: 'RK-2ND', a: 20 },
  'Mfiondu Kabengele': { s: 219, t: '2W', a: 29 },
  'Micah Peavy': { s: 215, t: 'RK-2ND', a: 25 },
  'Micah Potter': { s: 280, t: 'ROS', a: 28 },
  'Michael Porter Jr.': { s: 4081, t: 'DRK-EXT', a: 28 },
  'Mikal Bridges': { s: 3348, t: 'VET-EXT', a: 30 },
  'Mike Conley': { s: 245, t: 'FA', a: 39 },
  'Mikel Brown Jr.': { s: 879, t: 'RK-1ST', a: 20 },
  'Miles Bridges': { s: 2283, t: 'FA', a: 28 },
  'Miles McBride': { s: 396, t: 'VET-EXT', a: 26 },
  'Mitchell Robinson': { s: 1504, t: 'FA', a: 28 },
  'Mohamed Bamba': { s: 351, t: 'FA', a: 28 },
  'Mohamed Diawara': { s: 262, t: 'FA', a: 21 },
  'Morez Johnson Jr.': { s: 675, t: 'RK-1ST', a: 21 },
  'Moritz Wagner': { s: 900, t: 'FA', a: 29 },
  'Moses Moody': { s: 1250, t: 'RK-EXT', a: 24 },
  'Moses Wright': { s: 219, t: '2W', a: 28 },
  'Mouhamed Gueye': { s: 241, t: 'RK-2ND', a: 24 },
  'Moussa Cisse': { s: 219, t: 'FA', a: 24 },
  'Moussa Diabate': { s: 246, t: 'ROS', a: 25 },
  'Myles Turner': { s: 2658, t: 'FA', a: 30 },
  'Myron Gardner': { s: 258, t: 'ROS', a: 25 },
  'Nae\'qwan Tomlin': { s: 241, t: 'ROS', a: 26 },
  'Nah\'Shon Hyland': { s: 285, t: 'FA', a: 26 },
  'Naji Marshall': { s: 943, t: 'FA', a: 29 },
  'Nate Ament': { s: 550, t: 'RK-1ST', a: 20 },
  'Naz Reid': { s: 2328, t: 'FA', a: 27 },
  'Neemias Queta': { s: 267, t: 'FA', a: 27 },
  'Nemanja Bjelica': { s: 245, t: 'FA', a: 38 },
  'Nickeil Alexander-Walker': { s: 1440, t: 'S&T', a: 28 },
  'Nico Mannion': { s: 219, t: '2W', a: 25 },
  'Nicolas Batum': { s: 765, t: 'FA', a: 38 },
  'Nicolas Claxton': { s: 2332, t: 'FA', a: 27 },
  'Nicolo Melli': { s: 507, t: 'FA', a: 36 },
  'Nikola Jokic': { s: 5903, t: 'DVET-EXT', a: 31 },
  'Nikola Jovic': { s: 1620, t: 'RK-EXT', a: 23 },
  'Nikola Milutinov': { s: 317, t: '', a: 32 },
  'Nikola Topic': { s: 543, t: 'RK-1ST', a: 21 },
  'Nikola Vucevic': { s: 245, t: 'FA', a: 36 },
  'Nique Clifford': { s: 326, t: 'RK-1ST', a: 24 },
  'Noa Essengue': { s: 570, t: 'RK-1ST', a: 20 },
  'Noah Clowney': { s: 541, t: 'RK-1ST', a: 22 },
  'Noah Penda': { s: 215, t: 'RK-2ND', a: 22 },
  'Nolan Traore': { s: 400, t: 'RK-1ST', a: 20 },
  'Norchad Omier': { s: 219, t: '2W', a: 25 },
  'Norman Powell': { s: 2150, t: 'FA', a: 33 },
  'OG Anunoby': { s: 4250, t: 'FA', a: 29 },
  'Obi Toppin': { s: 1500, t: 'FA', a: 28 },
  'Olivier Sarr': { s: 245, t: '2W', a: 27 },
  'Olivier-Maxence Prosper': { s: 250, t: 'ROS', a: 24 },
  'Onyeka Okongwu': { s: 1610, t: 'RK-EXT', a: 26 },
  'Oso Ighodaro': { s: 230, t: 'RK-2ND', a: 24 },
  'Ousmane Dieng': { s: 575, t: 'FA', a: 23 },
  'P.J. Tucker': { s: 245, t: 'ROS', a: 41 },
  'PJ Washington': { s: 1981, t: 'VET-EXT', a: 28 },
  'Pacome Dadiet': { s: 298, t: 'RK-1ST', a: 21 },
  'Paolo Banchero': { s: 4124, t: 'DRK-EXT', a: 24 },
  'Pascal Siakam': { s: 4892, t: 'FA', a: 32 },
  'Pat Connaughton': { s: 382, t: 'ROS', a: 34 },
  'Patrick Baldwin Jr.': { s: 245, t: '2W', a: 24 },
  'Patrick Williams': { s: 1800, t: 'FA', a: 25 },
  'Patty Mills': { s: 245, t: 'FA', a: 38 },
  'Paul George': { s: 5413, t: 'FA', a: 36 },
  'Paul Reed': { s: 560, t: 'FA', a: 27 },
  'Payton Pritchard': { s: 777, t: 'RK-EXT', a: 29 },
  'Pelle Larsson': { s: 230, t: 'RK-2ND', a: 25 },
  'Pete Nance': { s: 254, t: 'FA', a: 26 },
  'Petteri Koponen': { s: 317, t: 'RK', a: 38 },
  'Peyton Watson': { s: 1307, t: 'RK-1ST', a: 24 },
  'Precious Achiuwa': { s: 548, t: 'FA', a: 27 },
  'Quentin Grimes': { s: 1395, t: 'FA', a: 26 },
  'Quenton Jackson': { s: 258, t: 'ROS', a: 28 },
  'Quinten Post': { s: 900, t: 'FA', a: 26 },
  'R.J. Barrett': { s: 2962, t: 'RK-EXT', a: 26 },
  'Rajon Rondo': { s: 245, t: 'FA', a: 40 },
  'Ramon Sessions': { s: 245, t: '', a: 40 },
  'Rasheer Fleming': { s: 215, t: 'RK-2ND', a: 22 },
  'Raul Neto': { s: 245, t: 'FA', a: 34 },
  'Reed Sheppard': { s: 1111, t: 'RK-1ST', a: 22 },
  'Reggie Bullock': { s: 245, t: 'FA', a: 35 },
  'Richard Jefferson': { s: 245, t: '', a: 46 },
  'Rob Dillingham': { s: 689, t: 'RK-1ST', a: 22 },
  'Robert Williams III': { s: 1400, t: 'VET-EXT', a: 29 },
  'Rodney Hood': { s: 245, t: 'FA', a: 34 },
  'Ron Harper Jr.': { s: 315, t: 'FA', a: 26 },
  'Ron Holland II': { s: 907, t: 'RK-1ST', a: 21 },
  'Rondae Hollis-Jefferson': { s: 245, t: 'ROS', a: 32 },
  'Royce O\'Neale': { s: 1088, t: 'FA', a: 33 },
  'Rudy Gobert': { s: 3650, t: 'VET-EXT', a: 34 },
  'Rui Hachimura': { s: 1400, t: 'FA', a: 28 },
  'Russell Westbrook': { s: 245, t: 'FA', a: 38 },
  'Ryan Conwell': { s: 136, t: 'RK-2ND', a: 22 },
  'Ryan Dunn': { s: 278, t: 'RK-1ST', a: 24 },
  'Ryan Kalkbrenner': { s: 241, t: 'RK-2ND', a: 25 },
  'Ryan Nembhard': { s: 215, t: 'ROS', a: 23 },
  'Ryan Rollins': { s: 400, t: 'FA', a: 24 },
  'Saben Lee': { s: 245, t: '2W', a: 27 },
  'Saddiq Bey': { s: 656, t: 'FA', a: 27 },
  'Sam Hauser': { s: 1085, t: 'VET-EXT', a: 29 },
  'Sam Merrill': { s: 916, t: 'FA', a: 30 },
  'Sandro Mamukelashvili': { s: 1300, t: 'FA', a: 27 },
  'Santi Aldama': { s: 1701, t: 'FA', a: 26 },
  'Scoot Henderson': { s: 1359, t: 'RK-1ST', a: 22 },
  'Scottie Barnes': { s: 4175, t: 'DRK-EXT', a: 25 },
  'Scotty Pippen Jr.': { s: 246, t: '', a: 26 },
  'Sergio de Larrea': { s: 318, t: 'RK-1ST', a: 21 },
  'Seth Curry': { s: 245, t: 'ROS', a: 36 },
  'Shabazz Napier': { s: 245, t: '', a: 35 },
  'Shaedon Sharpe': { s: 2009, t: 'RK-EXT', a: 23 },
  'Shai Gilgeous-Alexander': { s: 4081, t: 'DRK-EXT', a: 28 },
  'Sharife Cooper': { s: 245, t: '2W', a: 25 },
  'Sidy Cissoko': { s: 250, t: 'ROS', a: 22 },
  'Simone Fontecchio': { s: 245, t: 'FA', a: 31 },
  'Sion James': { s: 241, t: 'RK-2ND', a: 24 },
  'Spencer Jones': { s: 600, t: 'FA', a: 25 },
  'Stephen Curry': { s: 6259, t: 'VET-EXT', a: 38 },
  'Stephon Castle': { s: 1002, t: 'RK-1ST', a: 22 },
  'Steven Adams': { s: 1300, t: 'VET-EXT', a: 33 },
  'Sviatoslav Mykhailiuk': { s: 385, t: 'FA', a: 29 },
  'T.J. McConnell': { s: 1100, t: 'VET-EXT', a: 34 },
  'TJ Leaf': { s: 219, t: '2W', a: 29 },
  'Taelon Peter': { s: 219, t: 'E10', a: 24 },
  'Taj Gibson': { s: 382, t: 'ROS', a: 41 },
  'Taran Armstrong': { s: 219, t: '2W', a: 25 },
  'Tari Eason': { s: 1405, t: 'FA', a: 25 },
  'Tarik Biberovic': { s: 300, t: 'RK', a: 26 },
  'Tarris Reed Jr.': { s: 308, t: 'RK-1ST', a: 23 },
  'Taurean Prince': { s: 382, t: 'FA', a: 32 },
  'Taylor Hendricks': { s: 781, t: 'RK-1ST', a: 23 },
  'Terance Mann': { s: 1550, t: 'VET-EXT', a: 30 },
  'Terrence Ross': { s: 245, t: 'ROS', a: 35 },
  'Terrence Shannon Jr.': { s: 280, t: 'RK-1ST', a: 26 },
  'Thaddeus Young': { s: 245, t: 'ROS', a: 38 },
  'Thanasis Antetokounmpo': { s: 245, t: 'FA', a: 34 },
  'Theo Pinson': { s: 245, t: 'FA', a: 31 },
  'Thomas Bryant': { s: 245, t: 'FA', a: 29 },
  'Thomas Sorber': { s: 489, t: 'RK-1ST', a: 21 },
  'Tidjane Salaun': { s: 824, t: 'RK-1ST', a: 21 },
  'Tim Hardaway Jr.': { s: 606, t: 'FA', a: 34 },
  'Tobias Harris': { s: 1504, t: 'FA', a: 34 },
  'Tolu Smith III': { s: 241, t: 'ROS', a: 26 },
  'Tomas Satoransky': { s: 245, t: 'ROS', a: 35 },
  'Tony Bradley': { s: 245, t: 'ROS', a: 29 },
  'Tony Snell': { s: 245, t: 'FA', a: 35 },
  'Torrey Craig': { s: 245, t: 'ROS', a: 36 },
  'Toumani Camara': { s: 1808, t: 'VET-EXT', a: 26 },
  'Trae Young': { s: 4949, t: 'FA', a: 28 },
  'Trayce Jackson-Davis': { s: 241, t: 'RK-2ND', a: 26 },
  'Tre Johnson': { s: 865, t: 'RK-1ST', a: 20 },
  'Tre Jones': { s: 800, t: 'FA', a: 27 },
  'Tre Mann': { s: 800, t: 'FA', a: 25 },
  'Trendon Watford': { s: 245, t: 'FA', a: 26 },
  'Trent Forrest': { s: 245, t: 'ROS', a: 28 },
  'Trevelin Queen': { s: 219, t: '2W', a: 29 },
  'Trevon Brazile': { s: 136, t: 'RK-2ND', a: 24 },
  'Trevor Keels': { s: 245, t: '2W', a: 23 },
  'Trey Lyles': { s: 245, t: 'FA', a: 31 },
  'Trey Murphy III': { s: 2700, t: 'RK-EXT', a: 26 },
  'Tristan Da Silva': { s: 399, t: 'RK-1ST', a: 25 },
  'Tristan Thompson': { s: 245, t: 'FA', a: 35 },
  'Tristan Vukcevic': { s: 300, t: 'ROS', a: 23 },
  'Troy Daniels': { s: 245, t: 'ROS', a: 35 },
  'Ty Jerome': { s: 922, t: 'FA', a: 29 },
  'Ty Lawson': { s: 245, t: '', a: 39 },
  'TyTy Washington Jr.': { s: 245, t: '2W', a: 25 },
  'Tyler Herro': { s: 3300, t: 'RK-EXT', a: 27 },
  'Tyler Kolek': { s: 230, t: 'RK-2ND', a: 25 },
  'Tyrese Haliburton': { s: 4892, t: 'DRK-EXT', a: 26 },
  'Tyrese Martin': { s: 245, t: '2W', a: 27 },
  'Tyrese Maxey': { s: 4077, t: 'FA', a: 26 },
  'Tyrese Proctor': { s: 215, t: 'RK-2ND', a: 22 },
  'Tyus Jones': { s: 245, t: 'FA', a: 30 },
  'Udoka Azubuike': { s: 219, t: '2W', a: 27 },
  'Udonis Haslem': { s: 245, t: 'FA', a: 46 },
  'Usman Garuba': { s: 245, t: 'ROS', a: 24 },
  'VJ Edgecombe': { s: 1166, t: 'RK-1ST', a: 21 },
  'Victor Wembanyama': { s: 1687, t: 'RK-1ST', a: 23 },
  'Vit Krejci': { s: 267, t: 'FA', a: 26 },
  'Vlatko Cancar': { s: 245, t: 'FA', a: 29 },
  'Walker Kessler': { s: 3011, t: 'S&T', a: 25 },
  'Walter Clayton Jr.': { s: 419, t: 'RK-1ST', a: 23 },
  'Wendell Carter Jr.': { s: 1810, t: 'VET-EXT', a: 27 },
  'Wendell Moore Jr.': { s: 245, t: '2W', a: 25 },
  'Wesley Matthews': { s: 245, t: 'FA', a: 40 },
  'Will Barton': { s: 245, t: 'ROS', a: 36 },
  'Will Richard': { s: 215, t: 'RK-2ND', a: 24 },
  'Will Riley': { s: 369, t: 'RK-1ST', a: 20 },
  'Willy Hernangomez': { s: 464, t: 'FA', a: 32 },
  'Xavier Moon': { s: 219, t: '2W', a: 32 },
  'Xavier Tillman': { s: 245, t: 'FA', a: 28 },
  'Yang Hansen': { s: 464, t: 'RK-1ST', a: 21 },
  'Yanic Konan Niederhauser': { s: 288, t: 'RK-1ST', a: 23 },
  'Yaxel Lendeborg': { s: 610, t: 'RK-1ST', a: 24 },
  'Yves Missi': { s: 351, t: 'RK-1ST', a: 22 },
  'Zaccharie Risacher': { s: 1383, t: 'RK-1ST', a: 21 },
  'Zach Collins': { s: 850, t: 'VET-EXT', a: 29 },
  'Zach Edey': { s: 633, t: 'RK-1ST', a: 24 },
  'Zach LaVine': { s: 4897, t: 'FA', a: 31 },
  'Zeke Nnaji': { s: 747, t: 'RK-EXT', a: 26 },
  'Ziaire Williams': { s: 245, t: 'FA', a: 25 },
  'Zion Williamson': { s: 4217, t: 'DRK-EXT', a: 26 },
  'Zuby Ejiofor': { s: 345, t: 'RK-1ST', a: 22 },
  'Day’Ron Sharpe': { s: 1000, t: 'FA', a: 25 },
  'De’Aaron Fox': { s: 4949, t: 'DVET-EXT', a: 29 },
  'De’Andre Hunter': { s: 2491, t: 'RK-EXT', a: 29 },
  'De’Anthony Melton': { s: 606, t: 'FA', a: 28 },
  'D’Angelo Russell': { s: 597, t: 'FA', a: 30 },
  'E.J. Liddell': { s: 71, t: 'UD', a: 26 },
  'Ja’Kobe Walter': { s: 381, t: 'RK-1ST', a: 22 },
  'Kam Jones': { s: 108, t: 'UD', a: 24 },
  'Kel’el Ware': { s: 465, t: 'RK-1ST', a: 22 },
  'KyShawn George': { s: 311, t: 'RK-1ST', a: 23 },
  'Nae’Qwan Tomlin': { s: 241, t: 'ROS', a: 26 },
  'Royce O’Neale': { s: 1088, t: 'FA', a: 33 },
  'Tristan da Silva': { s: 399, t: 'RK-1ST', a: 25 },
  'CJ McCollum': { s: 2100, t: 'VET-EXT', a: 35 },
  'Dennis Schroder': { s: 1481, t: 'FA', a: 33 },
  'GG Jackson': { s: 241, t: 'ROS', a: 22 },
  'P.J. Washington': { s: 1981, t: 'VET-EXT', a: 28 },
  'RJ Barrett': { s: 2962, t: 'RK-EXT', a: 26 },
  'Christian Koloko': { s: 260, t: 'FA', a: 26 },
  'RayJ Dennis': { s: 260, t: 'FA', a: 26 },
  'Keshon Gilbert': { s: 220, t: 'FA', a: 26 },
  'Ochai Agbaji': { s: 750, t: 'FA', a: 26 },
  'Jalen Wilson': { s: 350, t: 'FA', a: 26 },
  'Chaney Johnson': { s: 260, t: 'FA', a: 26 },
  'Tyson Etienne': { s: 260, t: 'FA', a: 26 },
  'Malachi Smith': { s: 260, t: 'FA', a: 26 },
  'Trevon Scott': { s: 220, t: 'FA', a: 26 },
  'Dalano Banton': { s: 370, t: 'FA', a: 26 },
  'Amari Williams': { s: 220, t: 'FA', a: 26 },
  'John Tonje': { s: 220, t: 'FA', a: 26 },
  'PJ Hall': { s: 260, t: 'FA', a: 26 },
  'Nic Claxton': { s: 2500, t: 'FA', a: 26 },
  'Nick Richards': { s: 350, t: 'FA', a: 26 },
  'Yuki Kawamura': { s: 55, t: 'FA', a: 26 },
  'Mac McClung': { s: 55, t: 'FA', a: 26 },
  'Lachlan Olbrich': { s: 220, t: 'FA', a: 26 },
  'Tristan Enaruna': { s: 220, t: 'FA', a: 26 },
  'Riley Minix': { s: 220, t: 'FA', a: 26 },
  'John Poulakidas': { s: 260, t: 'FA', a: 26 },
  'Tyler Smith': { s: 220, t: 'FA', a: 26 },
  'Bruce Brown': { s: 2250, t: 'FA', a: 26 },
  'KJ Simpson': { s: 260, t: 'FA', a: 26 },
  'Ronald Holland II': { s: 1000, t: 'FA', a: 26 },
  'Isaac Jones': { s: 260, t: 'FA', a: 26 },
  'Tolu Smith': { s: 220, t: 'FA', a: 26 },
  'Nate Williams': { s: 350, t: 'FA', a: 26 },
  'LJ Cryer': { s: 350, t: 'FA', a: 26 },
  'Malevy Leons': { s: 220, t: 'FA', a: 26 },
  'JD Davison': { s: 220, t: 'FA', a: 26 },
  'Tristen Newton': { s: 220, t: 'FA', a: 26 },
  'Kobe Brown': { s: 350, t: 'FA', a: 26 },
  'Jalen Slawson': { s: 260, t: 'FA', a: 26 },
  'Ethan Thompson': { s: 260, t: 'FA', a: 26 },
  'Cam Christie': { s: 220, t: 'FA', a: 26 },
  'Sean Pedulla': { s: 220, t: 'FA', a: 26 },
  'Maxi Kleber': { s: 1100, t: 'FA', a: 26 },
  'Nick Smith Jr.': { s: 260, t: 'FA', a: 26 },
  'Drew Timme': { s: 260, t: 'FA', a: 26 },
  'Chris Manon': { s: 220, t: 'FA', a: 26 },
  'Javon Small': { s: 600, t: 'FA', a: 26 },
  'Jahmai Mashack': { s: 260, t: 'FA', a: 26 },
  'Dariq Whitehead': { s: 450, t: 'FA', a: 26 },
  'Adama Bal': { s: 220, t: 'FA', a: 26 },
  'Vladislav Goldin': { s: 220, t: 'FA', a: 26 },
  'Cormac Ryan': { s: 260, t: 'FA', a: 26 },
  'Bones Hyland': { s: 400, t: 'FA', a: 26 },
  'Julian Phillips': { s: 200, t: 'FA', a: 26 },
  'Enrique Freeman': { s: 220, t: 'FA', a: 26 },
  'Rocco Zikarsky': { s: 220, t: 'FA', a: 26 },
  'Mouhamadou Gueye': { s: 220, t: 'FA', a: 26 },
  'Zyon Pullin': { s: 220, t: 'FA', a: 26 },
  'Herbert Jones': { s: 1300, t: 'FA', a: 26 },
  'Hunter Dickinson': { s: 220, t: 'FA', a: 26 },
  'Jeremy Sochan': { s: 550, t: 'FA', a: 26 },
  'Trey Jemison III': { s: 260, t: 'FA', a: 26 },
  'Brooks Barnhizer': { s: 220, t: 'FA', a: 26 },
  'Jett Howard': { s: 600, t: 'FA', a: 26 },
  'Colin Castleton': { s: 220, t: 'FA', a: 26 },
  'Alex Morales': { s: 220, t: 'FA', a: 26 },
  'Caleb Love': { s: 350, t: 'FA', a: 26 },
  'Rayan Rupert': { s: 350, t: 'FA', a: 26 },
  'Dalen Terry': { s: 260, t: 'FA', a: 26 },
  'Pat Spencer': { s: 350, t: 'FA', a: 26 },
  'Koby Brea': { s: 220, t: 'FA', a: 26 },
  'CJ Huntley': { s: 220, t: 'FA', a: 26 },
  'Chris Youngblood': { s: 220, t: 'FA', a: 26 },
  'Jayson Kent': { s: 220, t: 'FA', a: 26 },
  'Jonathan Mogbo': { s: 350, t: 'FA', a: 26 },
  'Isaiah Stevens': { s: 220, t: 'FA', a: 26 },
  'Adam Flagler': { s: 220, t: 'FA', a: 26 },
  'David Jones Garcia': { s: 260, t: 'FA', a: 26 },
  'Harrison Ingram': { s: 220, t: 'FA', a: 26 },
  'Emanuel Miller': { s: 220, t: 'FA', a: 26 },
  'Chucky Hepburn': { s: 220, t: 'FA', a: 26 },
  'Svi Mykhailiuk': { s: 220, t: 'FA', a: 26 },
  'Oscar Tshiebwe': { s: 260, t: 'FA', a: 26 },
  'Blake Hinson': { s: 260, t: 'FA', a: 26 },
  'Elijah Harkless': { s: 260, t: 'FA', a: 26 },
  'Mo Bamba': { s: 220, t: 'FA', a: 26 },
  'Trey Alexander': { s: 220, t: 'FA', a: 26 },
  'Tamar Bates': { s: 55, t: 'FA', a: 26 },
  'Julian Reese': { s: 350, t: 'FA', a: 26 },
  'Jamir Watkins': { s: 55, t: 'FA', a: 26 },
};