// ============================================================
// 选秀/新秀相关数据（阶段1 外置）
// 纯数据，无函数依赖；由 __ai_app.html 在主逻辑前加载
// ============================================================

var MVP_STAR_NAMES = [
  'A-J-迪班萨', '达林-彼得森', '卡梅隆-布泽尔',
  '乔丹-史密斯二世', '泰兰-斯托克斯', '斯特凡-约克西莫维奇',
  '若阿金-布姆杰-布姆杰', '尼古拉-库斯图里卡', '马库斯-斯皮尔斯二世'
];

var DRAFT_CLASS_2026 = [
  { pick: 1, team: 'WAS', cn: 'A-J-迪班萨', pos: '前锋', height: '2.06米' },
  { pick: 2, team: 'UTA', cn: '达林-彼得森', pos: '后卫', height: '1.98米' },
  { pick: 3, team: 'MEM', cn: '卡梅隆-布泽尔', pos: '前锋', height: '2.06米' },
  { pick: 4, team: 'CHI', cn: '凯莱布-威尔逊', pos: '前锋', height: '2.08米' },
  { pick: 5, team: 'LAC', cn: '基顿-瓦格勒', pos: '后卫', height: '1.98米' },
  { pick: 6, team: 'BKN', cn: '米克尔-布朗-二世', pos: '后卫', height: '1.96米' },
  { pick: 7, team: 'SAC', cn: '达里乌斯-阿库夫-二世', pos: '后卫', height: '1.91米' },
  { pick: 8, team: 'ATL', cn: '金斯顿-弗莱明斯', pos: '后卫', height: '1.93米' },
  { pick: 9, team: 'DAL', cn: '莫雷兹-约翰逊-二世', pos: '前锋', height: '2.06米' },
  { pick: 10, team: 'MIL', cn: '布雷登-伯里斯', pos: '后卫', height: '1.93米' },
  { pick: 11, team: 'GSW', cn: '雅克塞尔-兰德伯格', pos: '前锋', height: '2.06米' },
  { pick: 12, team: 'OKC', cn: '阿戴-马拉', pos: '中锋', height: '2.21米' },
  { pick: 13, team: 'MIL', cn: '内特-阿门特', pos: '前锋', height: '2.08米' },
  { pick: 14, team: 'CHA', cn: '汉内斯-斯坦巴赫', pos: '前锋', height: '2.11米' },
  { pick: 15, team: 'CHI', cn: '戴林-斯温', pos: '后卫', height: '2.03米' },
  { pick: 16, team: 'OKC', cn: '班尼特-斯蒂尔茨', pos: '后卫', height: '1.93米' },
  { pick: 17, team: 'DET', cn: '埃布卡-奥科里', pos: '后卫', height: '1.88米' },
  { pick: 18, team: 'CHA', cn: '克里斯蒂安-安德森', pos: '后卫', height: '1.91米' },
  { pick: 19, team: 'TOR', cn: '艾伦-格雷夫斯', pos: '前锋', height: '2.06米' },
  { pick: 20, team: 'SAS', cn: '杰登-昆坦斯', pos: '前锋', height: '2.08米' },
  { pick: 21, team: 'MEM', cn: '卡里姆-洛佩兹', pos: '前锋', height: '2.03米' },
  { pick: 22, team: 'PHI', cn: '拉巴伦-菲隆-二世', pos: '后卫', height: '1.93米' },
  { pick: 23, team: 'ATL', cn: '祖比-埃吉奥福', pos: '前锋', height: '2.06米' },
  { pick: 24, team: 'LAL', cn: '卡梅隆-卡尔', pos: '后卫', height: '1.96米' },
  { pick: 25, team: 'DAL', cn: '塞尔希奥-德-拉雷亚', pos: '前锋', height: '1.98米' },
  { pick: 26, team: 'SAS', cn: '塔里斯-里德-二世', pos: '中锋', height: '2.11米' },
  { pick: 27, team: 'BOS', cn: '克里斯-塞纳克-二世', pos: '前锋', height: '2.11米' },
  { pick: 28, team: 'BKN', cn: '约书亚-杰斐逊', pos: '前锋', height: '2.06米' },
  { pick: 29, team: 'SAC', cn: '亚历克斯-卡拉班', pos: '前锋', height: '2.03米' },
  { pick: 30, team: 'PHX', cn: '科亚-皮特', pos: '前锋', height: '2.03米' },
  { pick: 31, team: 'HOU', cn: '布鲁斯-桑顿-二世', pos: '后卫', height: '1.88米' },
  { pick: 32, team: 'MEM', cn: '里奇-桑德斯', pos: '后卫', height: '1.96米' },
  { pick: 33, team: 'MIN', cn: '赛亚-埃文斯', pos: '后卫', height: '1.98米' },
  { pick: 34, team: 'CLE', cn: '米里克-托马斯', pos: '后卫', height: '1.96米' },
  { pick: 35, team: 'DEN', cn: '特雷文-布拉齐尔', pos: '前锋', height: '2.08米' },
  { pick: 36, team: 'LAC', cn: '巴巴-米勒', pos: '前锋', height: '2.11米' },
  { pick: 37, team: 'MIA', cn: '赖安-康威尔', pos: '后卫', height: '1.93米' },
  { pick: 38, team: 'IND', cn: '布雷登-史密斯', pos: '后卫', height: '1.83米' },
  { pick: 39, team: 'NYK', cn: '杰克-卡伊尔', pos: '后卫', height: '1.91米' },
  { pick: 40, team: 'BOS', cn: '狄龙-米切尔', pos: '前锋', height: '2.03米' },
  { pick: 41, team: 'OKC', cn: '奥特加-奥韦', pos: '后卫', height: '1.93米' },
  { pick: 42, team: 'SAS', cn: '贾科比-吉莱斯皮', pos: '后卫', height: '1.85米' },
  { pick: 43, team: 'BKN', cn: '泰勒-比洛多', pos: '前锋', height: '2.06米' },
  { pick: 44, team: 'SAS', cn: '马利克-布朗', pos: '前锋', height: '2.06米' },
  { pick: 45, team: 'SAC', cn: '伊曼纽尔-夏普', pos: '后卫', height: '1.91米' },
  { pick: 46, team: 'WAS', cn: '菲利克斯-奥帕拉', pos: '前锋', height: '2.11米' },
  { pick: 47, team: 'NYK', cn: '泰勒-尼克尔', pos: '前锋', height: '2.01米' },
  { pick: 48, team: 'DAL', cn: '托比-拉瓦尔', pos: '前锋', height: '2.03米' },
  { pick: 49, team: 'DEN', cn: '布莱斯-霍普金斯', pos: '前锋', height: '2.01米' },
  { pick: 50, team: 'TOR', cn: '贾登-布拉德利', pos: '后卫', height: '1.91米' },
  { pick: 51, team: 'ORL', cn: '伊赛亚-尼尔森', pos: '前锋', height: '2.08米' },
  { pick: 52, team: 'ATL', cn: '亨利-维萨尔', pos: '中锋', height: '2.13米' },
  { pick: 53, team: 'DET', cn: '乌戈纳-奥尼恩索', pos: '中锋', height: '2.13米' },
  { pick: 54, team: 'GSW', cn: '拉杰-琼斯', pos: '后卫', height: '2.01米' },
  { pick: 55, team: 'LAC', cn: '尼克-马蒂内利', pos: '前锋', height: '2.01米' },
  { pick: 56, team: 'DAL', cn: '弗谢沃洛德-伊什琴科', pos: '后卫', height: '1.91米' },
  { pick: 57, team: 'LAC', cn: '纳西斯-恩戈伊', pos: '中锋', height: '2.13米' },
  { pick: 58, team: 'NOP', cn: '贾伦-皮埃尔-二世', pos: '后卫', height: '1.96米' },
  { pick: 59, team: 'MIN', cn: '特雷-考夫曼-雷恩', pos: '前锋', height: '2.06米' },
  { pick: 60, team: 'MIL', cn: '马利克-刘易斯', pos: '前锋', height: '2.03米' },
];

var DRAFT_CLASS_2027 = [
  { pick: 4, en: "Bruce Branch", cn: "布鲁斯-布兰奇" },
  { pick: 5, en: "Caleb Holt", cn: "卡莱布-霍尔特" },
  { pick: 6, en: "Braylon Mullins", cn: "布雷隆-穆林斯" },
  { pick: 7, en: "Thomas Haugh", cn: "托马斯-霍" },
  { pick: 8, en: "Luigi Suigo", cn: "路易吉-苏伊戈" },
  { pick: 9, en: "Hugo Yimga Moukouri", cn: "雨果-伊姆加-穆库里" },
  { pick: 10, en: "Cameron Williams", cn: "卡梅伦-威廉姆斯" },
  { pick: 11, en: "Alijah Arenas", cn: "阿利贾-阿雷纳斯" },
  { pick: 12, en: "Motiejus Krivas", cn: "莫蒂耶乌斯-克里瓦斯" },
  { pick: 13, en: "Sayon Keita", cn: "萨永-凯塔" },
  { pick: 14, en: "Cameron Houindo", cn: "卡梅伦-乌因多" },
  { pick: 15, en: "Abdou Toure", cn: "阿卜杜-图雷" },
  { pick: 16, en: "Christian Collins", cn: "克里斯蒂安-科林斯" },
  { pick: 17, en: "Dylan Mingo", cn: "迪伦-明戈" },
  { pick: 18, en: "Cheickh Niang", cn: "谢赫-尼昂" },
  { pick: 19, en: "Amari Allen", cn: "阿马里-艾伦" },
  { pick: 20, en: "Malachi Moreno", cn: "玛拉基-莫雷诺" },
  { pick: 21, en: "Rueben Chinyelu", cn: "鲁本-奇涅卢" },
  { pick: 22, en: "Pavle Backo", cn: "帕夫莱-巴科" },
  { pick: 23, en: "Anthony Thompson", cn: "安东尼-汤普森" },
  { pick: 24, en: "Tounde Yessoufou", cn: "通德-耶苏富" },
  { pick: 25, en: "Dame Sarr", cn: "达梅-萨尔" },
  { pick: 26, en: "Moustapha Thiam", cn: "穆斯塔法-蒂亚姆" },
  { pick: 27, en: "Baba Oladotun", cn: "巴巴-奥拉多顿" },
  { pick: 28, en: "Mor Massamba Diop", cn: "莫尔-马桑巴-迪奥普" },
  { pick: 29, en: "Trey McKenney", cn: "特雷-麦肯尼" },
  { pick: 30, en: "Shelton Henderson", cn: "谢尔顿-亨德森" },
  { pick: 31, en: "Klark Riethauser", cn: "克拉克-里特豪泽" },
  { pick: 32, en: "Paul Mbiya", cn: "保罗-姆比亚" },
  { pick: 33, en: "Quentin Coleman", cn: "昆廷-科尔曼" },
  { pick: 34, en: "Milon Momcilovic", cn: "米隆-莫姆契洛维奇" },
  { pick: 35, en: "Brandon McCoy Jr.", cn: "布兰登-麦科伊二世" },
  { pick: 36, en: "Arafan Diane", cn: "阿拉凡-迪亚内" },
  { pick: 37, en: "David Mirkovic", cn: "大卫-米尔科维奇" },
  { pick: 38, en: "Matas Vokietaitis", cn: "马塔斯-沃基耶塔蒂斯" },
  { pick: 39, en: "Neoklis Avdalas", cn: "内奥克利斯-阿夫达拉斯" },
  { pick: 40, en: "Ivan Kharchenkov", cn: "伊万-哈尔琴科夫" },
  { pick: 41, en: "Alex Condon", cn: "亚历克斯-康登" },
  { pick: 42, en: "Miikka Muurinen", cn: "米卡-穆里宁" },
  { pick: 43, en: "Daniel Jacobsen", cn: "丹尼尔-雅各布森" },
  { pick: 44, en: "Billy Richmond", cn: "比利-里士满" },
  { pick: 45, en: "Matt Able", cn: "马特-阿布尔" },
  { pick: 46, en: "Coen Carr", cn: "科恩-卡尔" },
  { pick: 47, en: "John Blackwell", cn: "约翰-布莱克威尔" },
  { pick: 48, en: "Adam Atamna", cn: "亚当-阿塔姆纳" },
  { pick: 49, en: "Andrej Stojakovic", cn: "安德烈-斯托亚科维奇" },
  { pick: 50, en: "Paul McNeil Jr.", cn: "保罗-麦克尼尔二世" },
  { pick: 51, en: "Jacob Cofie", cn: "雅各布-科菲" },
  { pick: 52, en: "Tyler Tanner", cn: "泰勒-坦纳" },
  { pick: 53, en: "Juke Harris", cn: "朱克-哈里斯" },
  { pick: 54, en: "Flory Bidunga", cn: "弗洛里-比东加" },
  { pick: 55, en: "Cayden Boozer", cn: "凯登-布泽尔" },
  { pick: 56, en: "Matthys Mahop", cn: "马蒂斯-马霍普" },
  { pick: 57, en: "Oscar Wembanyama", cn: "奥斯卡-文班亚马" },
  { pick: 58, en: "JJ Andrews", cn: "J.J.-安德鲁斯" },
  { pick: 59, en: "Tomislav Ivisic", cn: "托米斯拉夫-伊维西奇" },
  { pick: 60, en: "Patrick Ngongba II", cn: "帕特里克-恩贡巴二世" },
  { pick: 61, en: "JT Toppin", cn: "J.T.-托平" },
  { pick: 62, en: "Alex Wilkins", cn: "亚历克斯-威尔金斯" },
  { pick: 63, en: "Pryce Sandfort", cn: "普赖斯-桑德福特" },
  { pick: 64, en: "Bryson Tiller", cn: "布莱森-蒂勒" },
  { pick: 65, en: "Anton Bonke", cn: "安东-邦克" },
  { pick: 66, en: "Jeremy Fears Jr.", cn: "杰里米-菲尔斯二世" },
  { pick: 67, en: "Michael Ruzic", cn: "迈克尔-鲁日奇" },
  { pick: 68, en: "Lucas Morillo", cn: "卢卡斯-莫里略" },
  { pick: 69, en: "Johann Grunloh", cn: "约翰-格伦洛" },
  { pick: 70, en: "Dash Daniels", cn: "达什-丹尼尔斯" },
  { pick: 71, en: "Solo Ball", cn: "索洛-鲍尔" },
  { pick: 72, en: "Omer Mayer", cn: "奥梅尔-迈耶" },
  { pick: 73, en: "Collin Chandler", cn: "科林-钱德勒" },
  { pick: 74, en: "Ian Jackson", cn: "伊恩-杰克逊" },
  { pick: 75, en: "Thijs De Ridder", cn: "泰斯-德里德尔" },
  { pick: 76, en: "Eric Reibe", cn: "埃里克-赖贝" },
  { pick: 77, en: "Nikolas Khamenia", cn: "尼古拉斯-哈梅尼亚" },
  { pick: 78, en: "Mario Saint-Supery", cn: "马里奥-圣叙佩里" },
  { pick: 79, en: "Jalen Haralson", cn: "杰伦-哈拉尔森" },
  { pick: 80, en: "Tay Kinney", cn: "泰-金尼" },
  { pick: 81, en: "Kanon Catchings", cn: "卡农-卡钦斯" },
  { pick: 82, en: "Silas Demary Jr.", cn: "赛拉斯-德马利二世" },
  { pick: 83, en: "Ognjen Srzentic", cn: "奥格年-斯尔珍蒂奇" },
  { pick: 84, en: "PJ Haggerty", cn: "P.J.-哈格蒂" },
  { pick: 85, en: "Amaël L'Etang", cn: "阿马埃尔-莱唐" },
  { pick: 86, en: "Braden Huff", cn: "布雷登-赫夫" },
  { pick: 87, en: "Nolan Winter", cn: "诺兰-温特" },
  { pick: 88, en: "Somto Cyril", cn: "索姆托-西里尔" },
  { pick: 89, en: "Elliott Cadeau", cn: "埃利奥特-卡多" },
  { pick: 90, en: "Kiyan Anthony", cn: "基扬-安东尼" },
  { pick: 91, en: "Bassala Bagayoka", cn: "巴萨拉-巴加约卡" },
  { pick: 92, en: "Mouhamed Faye", cn: "穆罕默德-法耶" },
  { pick: 93, en: "Robert Wright III", cn: "罗伯特-赖特三世" },
  { pick: 94, en: "Isiah Harwell", cn: "以赛亚-哈威尔" },
  { pick: 95, en: "Sadiq White", cn: "萨迪克-怀特" },
  { pick: 96, en: "London Jemison", cn: "伦敦-杰米森" },
  { pick: 97, en: "Dwayne Aristode", cn: "德韦恩-阿里斯托德" },
  { pick: 98, en: "Tahaad Pettiford", cn: "塔哈德-佩蒂福德" },
  { pick: 99, en: "Joseph Tugler", cn: "约瑟夫-塔格勒" },
  { pick: 100, en: "Jackson McAndrew", cn: "杰克逊-麦克安德鲁" },
];

var DRAFT_CLASS_2028 = [
  { pick: 4, en: "CJ Rosser", cn: "C.J.-罗瑟", pos: 'PF', height: '2.06米' },
  { pick: 5, en: "Beckham Black", cn: "贝克汉姆-布莱克", pos: 'PG', height: '1.91米' },
  { pick: 6, en: "Adan Diggs", cn: "亚当-迪格斯", pos: 'SG', height: '1.93米' },
  { pick: 7, en: "Nathan Soliman", cn: "内森-索利曼", pos: 'PF', height: '2.03米' },
  { pick: 8, en: "Paul Osaruyi", cn: "保罗-奥萨鲁伊", pos: 'PF', height: '2.08米' },
  { pick: 9, en: "Obinna Ekezie", cn: "奥宾纳-埃克济", pos: 'C', height: '2.13米' },
  { pick: 10, en: "Lewis Uvwo", cn: "刘易斯-乌沃", pos: 'C', height: '2.08米' },
  { pick: 11, en: "Demarcus Henry", cn: "德马库斯-亨利", pos: 'SF', height: '2.01米' },
  { pick: 12, en: "Messi Yangala", cn: "梅西-扬加拉", pos: 'SF', height: '2.03米' },
  { pick: 13, en: "Jason Crowe Jr.", cn: "杰森-克劳二世", pos: 'PG', height: '1.91米' },
  { pick: 14, en: "Jordan Page", cn: "乔丹-佩奇", pos: 'SG', height: '1.96米' },
  { pick: 15, en: "Stefan Vaaks", cn: "斯特凡-瓦克斯", pos: 'SF', height: '2.01米' },
  { pick: 16, en: "Fabian Kayser", cn: "法比安-凯泽", pos: 'SF', height: '2.03米' },
  { pick: 17, en: "Nasir (Rudy) Anderson", cn: "纳西尔-安德森（鲁迪）", pos: 'PG', height: '1.93米' },
  { pick: 18, en: "Luke Paul", cn: "卢克-保罗", pos: 'PG', height: '1.98米' },
  { pick: 19, en: "Caleb Gaskins", cn: "卡莱布-加斯金斯", pos: 'SF', height: '2.01米' },
  { pick: 20, en: "Malachi Jordan", cn: "玛拉基-乔丹", pos: 'SG', height: '1.96米' },
  { pick: 21, en: "Ryan Hampton", cn: "瑞安-汉普顿", pos: 'SG', height: '1.98米' },
  { pick: 22, en: "Egor Amosov", cn: "叶戈尔-阿莫索夫", pos: 'SF', height: '1.98米' },
  { pick: 23, en: "King Gibson", cn: "金-吉布森", pos: 'SG', height: '1.93米' },
  { pick: 24, en: "Tajh Ariza", cn: "塔伊-阿里扎", pos: 'SF', height: '2.07米' },
  { pick: 25, en: "Kager Knueppel", cn: "凯格-克努佩尔", pos: 'PF', height: '2.06米' },
  { pick: 26, en: "Austin Goosby", cn: "奥斯汀-古斯比", pos: 'SG', height: '1.96米' },
  { pick: 27, en: "Gabe Nesmith", cn: "加布-内史密斯", pos: 'SG', height: '1.96米' },
  { pick: 28, en: "Deron Rippey Jr.", cn: "德隆-里皮二世", pos: 'PG', height: '1.88米' },
  { pick: 29, en: "Killyan Toure", cn: "基利安-图雷", pos: 'PG', height: '1.91米' },
  { pick: 30, en: "Bryson Howard", cn: "布莱森-霍华德", pos: 'SG', height: '1.96米' },
  { pick: 31, en: "Petar Bjelica", cn: "佩塔尔-别利察", pos: 'C', height: '2.03米' },
  { pick: 32, en: "Lincoln Cosby", cn: "林肯-科斯比", pos: 'SF', height: '2.06米' },
  { pick: 33, en: "Sebastian Williams-Adams", cn: "塞巴斯蒂安-威廉姆斯-亚当斯", pos: 'PF', height: '2.03米' },
  { pick: 34, en: "Colben Landrew", cn: "科尔本-兰德鲁", pos: 'SG', height: '1.98米' },
  { pick: 35, en: "Jake Wilkins", cn: "杰克-威尔金斯", pos: 'SF', height: '2.06米' },
  { pick: 36, en: "Tony Bryant", cn: "托尼-布莱恩特", pos: 'PF', height: '2.06米' },
  { pick: 37, en: "Davis Fogle", cn: "戴维斯-福格尔", pos: 'SG', height: '2.01米' },
  { pick: 38, en: "Mathias Vazquez", cn: "马蒂亚斯-巴斯克斯", pos: 'SF', height: '2.03米' },
  { pick: 39, en: "Josh Leonard", cn: "乔什-伦纳德", pos: 'SG', height: '1.98米' },
  { pick: 40, en: "Adonis Ratliff", cn: "阿多尼斯-拉特利夫", pos: 'PF', height: '2.11米' },
  { pick: 41, en: "L.J. Smith", cn: "L.J.-史密斯", pos: 'SG', height: '1.93米' },
  { pick: 42, en: "Jasper Johnson", cn: "贾斯珀-约翰逊", pos: 'PG', height: '1.93米' },
  { pick: 43, en: "Abdramane Siby", cn: "阿卜杜拉马内-西比", pos: 'C', height: '2.13米' },
  { pick: 44, en: "CJ Ingram", cn: "C.J.-英格拉姆", pos: 'SF', height: '1.98米' },
  { pick: 45, en: "Godson Okokoh", cn: "戈德森-奥科科", pos: 'C', height: '2.03米' },
  { pick: 46, en: "Moustapha Diop", cn: "穆斯塔法-迪奥普", pos: 'PF', height: '2.11米' },
  { pick: 47, en: "Sinan Huan", cn: "西南-胡安", pos: 'C', height: '2.16米' },
  { pick: 48, en: "Isaiah Johnson", cn: "以赛亚-约翰逊", pos: 'PG', height: '1.85米' },
  { pick: 49, en: "Darrius Wabbington", cn: "达里厄斯-沃宾顿", pos: 'C', height: '2.08米' },
  { pick: 50, en: "Alex Constanza", cn: "亚历克斯-康斯坦萨", pos: 'SF', height: '2.03米' },
  { pick: 51, en: "Tyrone Jamison", cn: "泰龙-贾米森", pos: 'PG', height: '1.88米' },
  { pick: 52, en: "Jamier Jones", cn: "贾米尔-琼斯", pos: 'SF', height: '1.96米' },
  { pick: 53, en: "Jordan Scott", cn: "乔丹-斯科特", pos: 'SF', height: '2.01米' },
  { pick: 54, en: "Hugo Facorat", cn: "雨果-法科拉特", pos: 'PF', height: '2.08米' },
  { pick: 55, en: "Ethan Taylor", cn: "伊森-泰勒", pos: 'C', height: '2.16米' },
  { pick: 56, en: "Elijah Williams", cn: "以利亚-威廉姆斯", pos: 'SF', height: '1.96米' },
  { pick: 57, en: "Jacob Webber", cn: "雅各布-韦伯", pos: 'SG', height: '1.98米' },
  { pick: 58, en: "Kohl Rosario", cn: "科尔-罗萨里奥", pos: 'SG', height: '1.93米' },
  { pick: 59, en: "Dooney Johnson", cn: "杜尼-约翰逊", pos: 'PG', height: '1.93米' },
  { pick: 60, en: "Darius Ratliff", cn: "达里乌斯-拉特利夫", pos: 'PF', height: '2.11米' },
  { pick: 61, en: "Bukky Oboye", cn: "布基-奥博耶", pos: 'C', height: '2.16米' },
  { pick: 62, en: "Junior County", cn: "朱尼尔-康蒂", pos: 'SG', height: '1.93米' },
  { pick: 63, en: "Chase McCarty", cn: "蔡斯-麦卡蒂", pos: 'SF', height: '1.98米' },
  { pick: 64, en: "Jordan Ellerbee", cn: "乔丹-埃勒比", pos: 'PG', height: '1.88米' },
  { pick: 65, en: "Zion Green", cn: "锡安-格林", pos: 'PF', height: '2.03米' },
  { pick: 66, en: "Acaden Lewis", cn: "阿卡登-刘易斯", pos: 'PG', height: '1.88米' },
  { pick: 67, en: "J.P. Estrella", cn: "J.P.-埃斯特雷拉", pos: 'PF', height: '2.11米' },
  { pick: 68, en: "Elzie Harrington", cn: "埃尔齐-哈灵顿", pos: 'PG', height: '1.96米' },
  { pick: 69, en: "Adam Oumiddoch", cn: "亚当-乌米多赫", pos: 'SG', height: '1.96米' },
  { pick: 70, en: "Chris Washington Jr.", cn: "克里斯-华盛顿二世", pos: 'SF', height: '2.01米' },
  { pick: 71, en: "Cameron Holmes", cn: "卡梅伦-霍姆斯", pos: 'SG', height: '1.96米' },
  { pick: 72, en: "David Punch", cn: "大卫-潘奇", pos: 'PF', height: '2.01米' },
  { pick: 73, en: "Jeremy Jenkins", cn: "杰里米-詹金斯", pos: 'C', height: '2.01米' },
  { pick: 74, en: "Mahamadou Landoure", cn: "马哈马杜-兰杜雷", pos: 'C', height: '2.11米' },
  { pick: 75, en: "Martay Barnes", cn: "马泰-巴恩斯", pos: 'SG', height: '1.88米' },
  { pick: 76, en: "Sananda Fru", cn: "萨南达-弗鲁", pos: 'C', height: '2.11米' },
  { pick: 77, en: "TJ Crumble", cn: "T.J.-克朗布尔", pos: 'SF', height: '2.01米' },
  { pick: 78, en: "Sam Funches", cn: "萨姆-芬奇斯", pos: 'C', height: '2.08米' },
  { pick: 79, en: "Melih Tunca", cn: "梅利赫-通卡", pos: 'SG', height: '1.96米' },
  { pick: 80, en: "Niko Bundalo", cn: "尼科-本达洛", pos: 'PF', height: '2.08米' },
  { pick: 81, en: "Ismaila Diagne", cn: "伊斯梅拉-迪亚涅", pos: 'C', height: '2.11米' },
  { pick: 82, en: "Josh Irving", cn: "乔什-欧文", pos: 'C', height: '2.11米' },
  { pick: 83, en: "Jamari Phillips", cn: "贾马里-菲利普斯", pos: 'PG', height: '1.91米' },
  { pick: 84, en: "Dylan Grant", cn: "迪伦-格兰特", pos: 'SF', height: '1.98米' },
  { pick: 85, en: "Sebastian Wilkins", cn: "塞巴斯蒂安-威尔金斯", pos: 'SF', height: '2.03米' },
  { pick: 86, en: "Marcus Ponder", cn: "马库斯-庞德", pos: 'C', height: '2.13米' },
  { pick: 87, en: "Larry Johnson", cn: "拉里-约翰逊", pos: 'SG', height: '1.93米' },
  { pick: 88, en: "Xavion Staton", cn: "泽维恩-斯塔顿", pos: 'C', height: '2.13米' },
  { pick: 89, en: "Derrion Reid", cn: "德里恩-里德", pos: 'PF', height: '2.03米' },
  { pick: 90, en: "Dante Allen", cn: "但丁-艾伦", pos: 'SG', height: '1.93米' },
  { pick: 91, en: "Oswin Erhunmwunse", cn: "奥斯温-埃尔胡姆文塞", pos: 'C', height: '2.06米' },
  { pick: 92, en: "Arturas Butajevas", cn: "阿尔图拉斯-布塔耶瓦斯", pos: 'C', height: '2.08米' },
  { pick: 93, en: "Latrell Almond", cn: "拉特雷尔-阿尔蒙德", pos: 'PF', height: '2.03米' },
  { pick: 94, en: "Cam Scott", cn: "卡姆-斯科特", pos: 'SG', height: '1.96米' },
  { pick: 95, en: "Darrion Sutton", cn: "达里恩-萨顿", pos: 'SF', height: '2.03米' },
  { pick: 96, en: "Francis Chukwudebelu", cn: "弗朗西斯-丘克武德贝卢", pos: 'C', height: '2.08米' },
  { pick: 97, en: "Jermaine O'Neal Jr.", cn: "杰梅因-奥尼尔二世", pos: 'SF', height: '1.98米' },
  { pick: 98, en: "Cam Ward", cn: "卡姆-沃德", pos: 'PF', height: '2.03米' },
  { pick: 99, en: "Mercy Miller", cn: "梅西-米勒", pos: 'SG', height: '1.93米' },
  { pick: 100, en: "Ace Glass", cn: "艾斯-格拉斯", pos: 'SG', height: '1.91米' },
  { pick: 101, en: "John Bol", cn: "约翰-博尔", pos: 'C', height: '2.18米' },
  { pick: 102, en: "Qayden Samuels", cn: "凯登-塞缪尔斯", pos: 'SF', height: '1.96米' },
  { pick: 103, en: "Annor Boateng", cn: "安诺-博阿滕", pos: 'SG', height: '1.96米' },
  { pick: 104, en: "Darren Harris", cn: "达伦-哈里斯", pos: 'SG', height: '1.96米' },
  { pick: 105, en: "Fedor Zugic", cn: "费多尔-祖吉奇", pos: 'SG', height: '1.98米' },
  { pick: 106, en: "Sir Mohammed", cn: "西尔-穆罕默德", pos: 'SF', height: '1.98米' },
  { pick: 107, en: "Aaron Rowe Jr.", cn: "阿龙-罗二世", pos: 'PG', height: '1.85米' },
  { pick: 108, en: "Ahmad Nowell", cn: "艾哈迈德-诺维尔", pos: 'PG', height: '1.83米' },
  { pick: 109, en: "Badara Diakite", cn: "巴达拉-迪亚基特", pos: 'C', height: '2.08米' },
  { pick: 110, en: "Jovani Ruff", cn: "约瓦尼-拉夫", pos: 'SG', height: '1.96米' },
  { pick: 111, en: "Henry Robinson Jr.", cn: "亨利-鲁宾逊二世", pos: 'SF', height: '2.01米' },
  { pick: 112, en: "Chidi Nwigwe", cn: "奇迪-恩维格韦", pos: 'SG', height: '1.98米' },
  { pick: 113, en: "Felipe Quinones", cn: "费利佩-基尼奥内斯", pos: 'SG', height: '1.96米' },
  { pick: 114, en: "Jaden Toombs", cn: "杰登-图姆斯", pos: 'C', height: '2.06米' },
  { pick: 115, en: "Jacob Furphy", cn: "雅各布-弗菲", pos: 'SG', height: '1.96米' },
  { pick: 116, en: "JJ Mandaquit", cn: "J.J.-曼达基特", pos: 'PG', height: '1.85米' },
  { pick: 117, en: "Bryce James", cn: "布莱斯-詹姆斯", pos: 'SF', height: '1.98米' },
  { pick: 118, en: "Julius Halaifonua", cn: "朱利叶斯-哈莱福努阿", pos: 'C', height: '2.11米' },
  { pick: 119, en: "RJ Jones", cn: "R.J.-琼斯", pos: 'PF', height: '2.03米' },
  { pick: 120, en: "Samis Calderon", cn: "萨米斯-卡尔德隆", pos: 'SF', height: '2.01米' },
  { pick: 121, en: "Jahki Howard", cn: "贾基-霍华德", pos: 'SF', height: '1.97米' },
  { pick: 122, en: "Naasir Cunningham", cn: "纳西尔-坎宁安", pos: 'SF', height: '2.01米' },
  { pick: 123, en: "James Brown", cn: "詹姆斯-布朗", pos: 'PF', height: '2.03米' },
  { pick: 124, en: "Bryce Heard", cn: "布莱斯-赫德", pos: 'SF', height: '1.96米' },
  { pick: 125, en: "BJ Davis-Ray", cn: "B.J.-戴维斯-雷", pos: 'SG', height: '1.96米' },
  { pick: 126, en: "Alier Maluk", cn: "阿利尔-马卢克", pos: 'C', height: '2.11米' },
  { pick: 127, en: "Chris Nwuli", cn: "克里斯-恩武利", pos: 'PF', height: '2.01米' },
  { pick: 128, en: "Jayden Williams", cn: "杰登-威廉姆斯", pos: 'PF', height: '2.06米' },
  { pick: 129, en: "Jalen Montonati", cn: "杰伦-蒙托纳蒂", pos: 'SF', height: '2.01米' },
  { pick: 130, en: "Kur Teng", cn: "库尔-滕", pos: 'SG', height: '1.93米' },
  { pick: 131, en: "Ace Flagg", cn: "艾斯-弗拉格", pos: 'SF', height: '2.01米' },
  { pick: 132, en: "Efeosa Oliogu", cn: "埃费奥萨-奥利奥古", pos: 'SF', height: '1.98米' },
  { pick: 133, en: "Eli Ellis", cn: "伊莱-埃利斯", pos: 'PG', height: '1.83米' },
  { pick: 134, en: "Rakease Passmore", cn: "拉基斯-帕斯莫尔", pos: 'SF', height: '1.98米' },
  { pick: 135, en: "Robert Hinton", cn: "罗伯特-欣顿", pos: 'SG', height: '1.96米' },
  { pick: 136, en: "Josiah Moseley", cn: "约西亚-莫斯利", pos: 'SF', height: '2.01米' },
  { pick: 137, en: "Andrej Kostic", cn: "安德烈-科斯蒂奇", pos: 'SG', height: '1.98米' },
  { pick: 138, en: "Taison Chatman", cn: "泰森-查特曼", pos: 'SG', height: '1.93米' },
  { pick: 139, en: "Jason Asemota", cn: "杰森-阿塞莫塔", pos: 'SF', height: '2.03米' },
];

var DRAFT_CLASS_2029 = [
  { pick: 1, en: "A.J. Williams", cn: "A.J.-威廉姆斯", pos: 'SF', height: '1.98米' },
  { pick: 2, en: "Isaiah Hamilton", cn: "以赛亚-汉密尔顿", pos: 'SF', height: '2.01米' },
  { pick: 3, en: "Yann Kamagate", cn: "扬-卡马加特", pos: 'C', height: '2.16米' },
  { pick: 4, en: "Jan Cerdan", cn: "扬-塞尔丹", pos: 'SF', height: '2.06米' },
  { pick: 5, en: "Colton Hiller", cn: "科尔顿-希勒", pos: 'SG', height: '1.98米' },
  { pick: 6, en: "Eric Dampier Jr.", cn: "埃里克-丹皮尔二世", pos: 'C', height: '2.11米' },
  { pick: 7, en: "Bamba Touray", cn: "班巴-图雷", pos: 'C', height: '2.13米' },
  { pick: 8, en: "Bentley Lusakueno", cn: "本特利-卢萨奎诺", pos: 'PF', height: '2.08米' },
  { pick: 9, en: "Rhys Robinson", cn: "里斯-罗宾逊", pos: 'PG', height: '2.01米' },
  { pick: 10, en: "Myles Hayes", cn: "迈尔斯-海斯", pos: 'SG', height: '1.96米' },
  { pick: 11, en: "Soumalia Keita", cn: "苏马利亚-凯塔", pos: 'C', height: '2.08米' },
  { pick: 12, en: "Evan Willis", cn: "埃文-威利斯", pos: 'SF', height: '2.03米' },
  { pick: 13, en: "Benjamin Berrouet", cn: "本杰明-贝鲁埃", pos: 'PF', height: '2.03米' },
  { pick: 14, en: "Toni Garma", cn: "托尼-加尔马", pos: 'SG', height: '1.93米' },
  { pick: 15, en: "Quinton Wilson", cn: "昆顿-威尔逊", pos: 'SG', height: '1.93米' },
  { pick: 16, en: "Javon Bardwell", cn: "贾文-巴德韦尔", pos: 'SF', height: '1.98米' },
  { pick: 17, en: "Jeremy Gohier", cn: "杰里米-戈希耶", pos: 'C', height: '2.29米' },
  { pick: 18, en: "Dylan Betts", cn: "迪伦-贝茨", pos: 'C', height: '2.18米' },
  { pick: 19, en: "Reese Alston", cn: "里斯-阿尔斯顿", pos: 'PG', height: '1.88米' },
  { pick: 20, en: "Miles Simpson", cn: "迈尔斯-辛普森", pos: 'SF', height: '1.96米' },
  { pick: 21, en: "Xavier Young", cn: "泽维尔-扬", pos: 'C', height: '2.08米' },
  { pick: 22, en: "Noah Washington", cn: "诺亚-华盛顿", pos: 'SF', height: '1.96米' },
  { pick: 23, en: "Logan Chwastyk", cn: "洛根-赫瓦斯提克", pos: 'PF', height: '2.08米' },
  { pick: 24, en: "Josiah Rose", cn: "约西亚-罗斯", pos: 'SG', height: '1.91米' },
  { pick: 25, en: "Dawson Battie", cn: "道森-巴蒂", pos: 'PF', height: '2.06米' },
  { pick: 26, en: "Shalen Sheppard", cn: "沙伦-谢泼德", pos: 'PF', height: '2.03米' },
  { pick: 27, en: "Kevin Wheatley Jr.", cn: "凯文-惠特利二世", pos: 'SF', height: '1.98米' },
  { pick: 28, en: "Liam Mitakaro", cn: "利亚姆-米塔卡罗", pos: 'PG', height: '1.93米' },
  { pick: 29, en: "Peter Julius", cn: "彼得-朱利叶斯", pos: 'C', height: '2.06米' },
  { pick: 30, en: "Howard Williams", cn: "霍华德-威廉姆斯", pos: 'SF', height: '2.01米' },
  { pick: 31, en: "Moussa Kamissoko", cn: "穆萨-卡米索科", pos: 'PF', height: '2.03米' },
  { pick: 32, en: "Gangaly Diallo", cn: "甘加利-迪亚洛", pos: 'C', height: '2.16米' },
  { pick: 33, en: "Ikenna Alozie", cn: "伊肯纳-阿洛齐", pos: 'SG', height: '1.88米' },
  { pick: 34, en: "Jakyi Miles", cn: "贾基-迈尔斯", pos: 'PG', height: '1.93米' },
  { pick: 35, en: "Mahamadou Diop", cn: "马哈马杜-迪奥普", pos: 'C', height: '2.11米' },
  { pick: 36, en: "Messie-Guethan Iwani", cn: "梅西-盖坦-伊瓦尼", pos: 'PF', height: '2.03米' },
  { pick: 37, en: "Kameron Mercer", cn: "卡梅隆-默瑟", pos: 'SF', height: '1.98米' },
  { pick: 38, en: "Ahmed Nur", cn: "艾哈迈德-努尔", pos: 'PF', height: '2.03米' },
  { pick: 39, en: "Quinn Costello", cn: "奎因-科斯特洛", pos: 'PF', height: '2.08米' },
  { pick: 40, en: "Omer Kutluay", cn: "奥梅尔-库特卢艾", pos: 'PG', height: '1.91米' },
  { pick: 41, en: "DJ Okoth", cn: "D.J.-奥科特", pos: 'SF', height: '1.98米' },
  { pick: 42, en: "Isaiah Hill", cn: "以赛亚-希尔", pos: 'PF', height: '2.08米' },
  { pick: 43, en: "Roko Jerkic", cn: "罗科-耶尔基奇", pos: 'SF', height: '1.98米' },
  { pick: 44, en: "Jalen Davis", cn: "杰伦-戴维斯", pos: 'SG', height: '1.91米' },
  { pick: 45, en: "Maximo Adams", cn: "马克西莫-亚当斯", pos: 'SF', height: '2.01米' },
  { pick: 46, en: "Terrell Jackson", cn: "特雷尔-杰克逊", pos: 'PF', height: '2.06米' },
  { pick: 47, en: "Kinston Knueppel", cn: "金斯顿-克努佩尔", pos: 'SF', height: '1.96米' },
  { pick: 48, en: "Cherif Millogo", cn: "谢里夫-米洛戈", pos: 'C', height: '2.18米' },
  { pick: 49, en: "Lukas Nikola Bojovic", cn: "卢卡斯-尼古拉-博约维奇", pos: 'PG', height: '1.96米' },
  { pick: 50, en: "Jasiah Jervis", cn: "贾西亚-杰维斯", pos: 'SG', height: '1.93米' },
  { pick: 51, en: "RJ Moore", cn: "R.J.-摩尔", pos: 'SG', height: '1.98米' },
  { pick: 52, en: "NaVorro Bowman Jr.", cn: "纳沃罗-鲍曼二世", pos: 'PG', height: '1.91米' },
  { pick: 53, en: "Joseph Tala", cn: "约瑟夫-塔拉", pos: 'SF', height: '1.98米' },
  { pick: 54, en: "Miles Sadler", cn: "迈尔斯-萨德勒", pos: 'PG', height: '1.80米' },
  { pick: 55, en: "Chase Smith", cn: "蔡斯-史密斯", pos: 'PF', height: '2.06米' },
  { pick: 56, en: "Maxime Meyer", cn: "马克西姆-迈耶", pos: 'C', height: '2.16米' },
  { pick: 57, en: "Cayden Daughtry", cn: "凯登-道特里", pos: 'PG', height: '1.83米' },
  { pick: 58, en: "Devin Cleveland", cn: "德文-克利夫兰", pos: 'SG', height: '1.91米' },
  { pick: 59, en: "Livio Berlingeri", cn: "利维奥-贝林杰里", pos: 'SG', height: '1.96米' },
  { pick: 60, en: "Darius Karutasu", cn: "达里乌斯-卡鲁塔苏", pos: 'SF', height: '2.01米' },
  { pick: 61, en: "Strahinja Zelic", cn: "斯特拉希尼亚-泽利奇", pos: 'C', height: '2.08米' },
  { pick: 62, en: "Ethan Harris", cn: "伊森-哈里斯", pos: 'PF', height: '2.06米' },
  { pick: 63, en: "Chris Paul II", cn: "克里斯-保罗二世", pos: 'PG', height: '1.80米' },
  { pick: 64, en: "Josh Lowery", cn: "乔什-洛厄里", pos: 'SG', height: '1.98米' },
  { pick: 65, en: "Martin Sibal", cn: "马丁-西巴尔", pos: 'C', height: '2.18米' },
  { pick: 66, en: "Aziz Olajuwon", cn: "阿齐兹-奥拉朱旺", pos: 'SF', height: '1.98米' },
  { pick: 67, en: "Nash Avery", cn: "纳什-埃弗里", pos: 'PF', height: '2.01米' },
  { pick: 68, en: "Jaylen Mitchell", cn: "杰伦-米切尔", pos: 'PF', height: '2.01米' },
  { pick: 69, en: "Kamsi Awaka", cn: "卡姆西-阿瓦卡", pos: 'C', height: '2.06米' },
  { pick: 70, en: "Luke Ertel", cn: "卢克-埃特尔", pos: 'PG', height: '1.88米' },
  { pick: 71, en: "Jagmeet Singh", cn: "贾格米特-辛格", pos: 'C', height: '2.24米' },
  { pick: 72, en: "Markuss Jahovics", cn: "马库斯-亚霍维奇", pos: 'SG', height: '1.96米' },
  { pick: 73, en: "Jadyn Jenkins", cn: "杰丁-詹金斯", pos: 'C', height: '2.06米' },
  { pick: 74, en: "Amari Williams", cn: "阿马里-威廉姆斯", pos: 'PF', height: '2.06米' },
  { pick: 75, en: "Darius Bivins", cn: "达里乌斯-比文斯", pos: 'PG', height: '1.80米' },
  { pick: 76, en: "Jeremiah Profit", cn: "杰里迈亚-普罗菲特", pos: 'SG', height: '1.93米' },
];

var DRAFT_CLASS_2030 = [
  { pick: 1, en: "Mohamed Dabone", cn: "穆罕默德-达博内", pos: 'PF', height: '2.08米' },
  { pick: 2, en: "JJ Crawford", cn: "J.J.-克劳福德", pos: 'SG', height: '1.93米' },
  { pick: 3, en: "Cayden Gaskins", cn: "凯登-加斯金斯", pos: 'PF', height: '2.06米' },
  { pick: 4, en: "RJ Evans", cn: "R.J.-埃文斯", pos: 'SF', height: '1.96米' },
  { pick: 5, en: "David Johnson", cn: "大卫-约翰逊", pos: 'SF', height: '2.03米' },
  { pick: 6, en: "Flory Kuminga", cn: "弗洛里-库明加", pos: 'SF', height: '2.01米' },
  { pick: 7, en: "Austin Leonard", cn: "奥斯汀-伦纳德", pos: 'SG', height: '1.93米' },
  { pick: 8, en: "Grant Duggins", cn: "格兰特-达金斯", pos: 'C', height: '2.06米' },
  { pick: 9, en: "Draydne McDaniel", cn: "德雷德恩-麦克丹尼尔", pos: 'SF', height: '2.01米' },
  { pick: 10, en: "Chudier Diew Yak", cn: "丘迪尔-迪尤-亚克", pos: 'C', height: '2.06米' },
  { pick: 11, en: "Alex Alexander", cn: "亚历克斯-亚历山大", pos: 'C', height: '2.08米' },
  { pick: 12, en: "Mamadou Issa Sow", cn: "马马杜-伊萨-索乌", pos: 'C', height: '2.08米' },
  { pick: 13, en: "Quali Giran", cn: "夸利-吉兰", pos: 'PG', height: '1.83米' },
  { pick: 14, en: "Josiah Brooks", cn: "约西亚-布鲁克斯", pos: 'PG', height: '1.88米' },
  { pick: 15, en: "Jayden Davis", cn: "杰登-戴维斯", pos: 'SF', height: '2.01米' },
  { pick: 16, en: "Cadien Hudson", cn: "卡迪恩-哈德森", pos: 'SF', height: '2.01米' },
  { pick: 17, en: "William Phillips", cn: "威廉-菲利普斯", pos: 'SF', height: '1.98米' },
  { pick: 18, en: "Mason Grivna", cn: "梅森-格里夫纳", pos: 'C', height: '2.11米' },
  { pick: 19, en: "Isaiah Rider IV", cn: "以赛亚-赖德四世", pos: 'PG', height: '1.88米' },
  { pick: 20, en: "Mateen Cleaves Jr.", cn: "马廷-克利夫斯二世", pos: 'SG', height: '1.93米' },
  { pick: 21, en: "Wekem Agamba", cn: "韦凯姆-阿甘巴", pos: 'C', height: '2.08米' },
  { pick: 22, en: "Majok Ater", cn: "马约克-阿特", pos: 'C', height: '2.08米' },
  { pick: 23, en: "Aaron Parker", cn: "阿龙-帕克", pos: 'PF', height: '2.01米' },
  { pick: 24, en: "MJ Postell", cn: "M.J.-波斯泰尔", pos: 'SG', height: '1.93米' },
  { pick: 25, en: "Bronx Ganaway", cn: "布朗克斯-加纳韦", pos: 'PF', height: '2.03米' },
  { pick: 26, en: "King Bacot", cn: "金-巴科特", pos: 'PG', height: '1.91米' },
  // 名单不足 30 人，以下 4 人为假人填充
  { pick: 27, en: "Trey Marbury", cn: "特雷-马布里", pos: 'PG', height: '1.91米' },
  { pick: 28, en: "Cam Reed", cn: "卡姆-里德", pos: 'SG', height: '1.96米' },
  { pick: 29, en: "Eli Banks", cn: "伊莱-班克斯", pos: 'SF', height: '2.01米' },
  { pick: 30, en: "Kofi Mensah", cn: "科菲-门萨", pos: 'C', height: '2.13米' },
];

var STAR_ROOKIES = [
  { en: "Jordan Smith Jr.", cn: "乔丹-史密斯二世", pick: 1, ovr: 85 },
  { en: "Tyran Stokes", cn: "泰兰-斯托克斯", pick: 2, ovr: 85 },
  { en: "Stefan Joksimovic", cn: "斯特凡-约克西莫维奇", pick: 3, ovr: 85 },
  { en: "Joaquim Boumtje Boumtje", cn: "若阿金-布姆杰-布姆杰", pick: 1, ovr: 85 },
  { en: "Nikola Kusturica", cn: "尼古拉-库斯图里卡", pick: 2, ovr: 85 },
  { en: "Marcus Spears Jr.", cn: "马库斯-斯皮尔斯二世", pick: 3, ovr: 85 },
];

var DRAFT_FAKE_POOL = [
  { en: "Jay Carter", cn: "杰伊-卡特", pos: 'PG', height: '1.88米' },
  { en: "Darius Boone", cn: "达里乌斯-布恩", pos: 'SG', height: '1.93米' },
  { en: "Malik Grant", cn: "马利克-格兰特", pos: 'SF', height: '1.98米' },
  { en: "Evan Brooks", cn: "埃文-布鲁克斯", pos: 'PF', height: '2.03米' },
  { en: "Marcus Hill", cn: "马库斯-希尔", pos: 'C', height: '2.08米' },
  { en: "Tyler Scott", cn: "泰勒-斯科特", pos: 'PG', height: '1.85米' },
  { en: "Devon Price", cn: "德文-普赖斯", pos: 'SG', height: '1.96米' },
  { en: "Jordan Miles", cn: "乔丹-迈尔斯", pos: 'SF', height: '2.01米' },
  { en: "Andre Cole", cn: "安德烈-科尔", pos: 'PF', height: '2.06米' },
  { en: "Moses Young", cn: "摩西-扬", pos: 'C', height: '2.11米' },
  { en: "Chris Ford", cn: "克里斯-福特", pos: 'PG', height: '1.91米' },
  { en: "Isaiah Reed", cn: "以赛亚-里德", pos: 'SG', height: '1.98米' },
  { en: "Jalen Brooks", cn: "杰伦-布鲁克斯", pos: 'SF', height: '2.03米' },
  { en: "Nate Simmons", cn: "内特-西蒙斯", pos: 'PF', height: '2.08米' },
  { en: "Omar White", cn: "奥马尔-怀特", pos: 'C', height: '2.16米' },
  { en: "Rashad Green", cn: "拉沙德-格林", pos: 'PG', height: '1.88米' },
  { en: "Kendall Fox", cn: "肯德尔-福克斯", pos: 'SG', height: '1.93米' },
  { en: "Trevor Page", cn: "特雷弗-佩奇", pos: 'SF', height: '1.98米' },
  { en: "Damian Cross", cn: "达米安-克罗斯", pos: 'PF', height: '2.03米' },
  { en: "Cedric Lane", cn: "塞德里克-莱恩", pos: 'C', height: '2.08米' },
  { en: "Xavier Moore", cn: "泽维尔-摩尔", pos: 'PG', height: '1.85米' },
  { en: "Brandon Cole", cn: "布兰登-科尔", pos: 'SG', height: '1.96米' },
  { en: "Anthony Wade", cn: "安东尼-韦德", pos: 'SF', height: '2.01米' },
  { en: "Reggie Stone", cn: "雷吉-斯通", pos: 'PF', height: '2.06米' },
  { en: "Tyrone Bass", cn: "泰龙-巴斯", pos: 'C', height: '2.11米' },
  { en: "Quentin Hall", cn: "昆廷-霍尔", pos: 'PG', height: '1.91米' },
  { en: "Dante Young", cn: "但丁-扬", pos: 'SG', height: '1.96米' },
  { en: "Sheldon Price", cn: "谢尔顿-普赖斯", pos: 'SF', height: '2.01米' },
  { en: "Maurice Bell", cn: "莫里斯-贝尔", pos: 'PF', height: '2.03米' },
  { en: "Colby Hart", cn: "科尔比-哈特", pos: 'C', height: '2.13米' },
].map(function(x, i) { return { pick: i + 1, en: x.en, cn: x.cn, pos: x.pos, height: x.height }; });

var FAKE_FIRST_NAMES = [
  { en: 'Jay', cn: '杰伊' }, { en: 'Darius', cn: '达里乌斯' }, { en: 'Malik', cn: '马利克' },
  { en: 'Evan', cn: '埃文' }, { en: 'Marcus', cn: '马库斯' }, { en: 'Tyler', cn: '泰勒' },
  { en: 'Devon', cn: '德文' }, { en: 'Jordan', cn: '乔丹' }, { en: 'Andre', cn: '安德烈' },
  { en: 'Moses', cn: '摩西' }, { en: 'Chris', cn: '克里斯' }, { en: 'Isaiah', cn: '以赛亚' },
  { en: 'Jalen', cn: '杰伦' }, { en: 'Nate', cn: '内特' }, { en: 'Omar', cn: '奥马尔' },
  { en: 'Rashad', cn: '拉沙德' }, { en: 'Kendall', cn: '肯德尔' }, { en: 'Trevor', cn: '特雷弗' },
  { en: 'Damian', cn: '达米安' }, { en: 'Cedric', cn: '塞德里克' }, { en: 'Xavier', cn: '泽维尔' },
  { en: 'Brandon', cn: '布兰登' }, { en: 'Anthony', cn: '安东尼' }, { en: 'Reggie', cn: '雷吉' },
  { en: 'Tyrone', cn: '泰龙' }, { en: 'Quentin', cn: '昆廷' }, { en: 'Dante', cn: '但丁' },
  { en: 'Sheldon', cn: '谢尔顿' }, { en: 'Maurice', cn: '莫里斯' }, { en: 'Colby', cn: '科尔比' },
  { en: 'Cameron', cn: '卡梅隆' }, { en: 'DeAndre', cn: '德安德烈' }, { en: 'Elijah', cn: '以利亚' },
  { en: 'Gavin', cn: '加文' }, { en: 'Hunter', cn: '亨特' }, { en: 'Isaac', cn: '艾萨克' },
  { en: 'Jamal', cn: '贾马尔' }, { en: 'Kobe', cn: '科比' }, { en: 'Lamar', cn: '拉马尔' },
  { en: 'Miles', cn: '迈尔斯' }, { en: 'Noah', cn: '诺亚' }, { en: 'Oscar', cn: '奥斯卡' },
  { en: 'Preston', cn: '普雷斯顿' }, { en: 'Quincy', cn: '昆西' }, { en: 'Roman', cn: '罗曼' },
  { en: 'Seth', cn: '塞斯' }, { en: 'Terrence', cn: '特伦斯' }, { en: 'Victor', cn: '维克托' },
  { en: 'Wesley', cn: '韦斯利' }, { en: 'Xander', cn: '赞德' }, { en: 'Yosef', cn: '约瑟夫' },
  { en: 'Zion', cn: '锡安' }, { en: 'Aaron', cn: '阿龙' }, { en: 'Bryson', cn: '布莱森' },
  { en: 'Corey', cn: '科里' }, { en: 'Dillon', cn: '迪伦' }, { en: 'Emanuel', cn: '伊曼纽尔' },
  { en: 'Felix', cn: '费利克斯' }, { en: 'Grant', cn: '格兰特' }, { en: 'Ivan', cn: '伊万' },
];

var FAKE_LAST_NAMES = [
  { en: 'Carter', cn: '卡特' }, { en: 'Boone', cn: '布恩' }, { en: 'Grant', cn: '格兰特' },
  { en: 'Brooks', cn: '布鲁克斯' }, { en: 'Hill', cn: '希尔' }, { en: 'Scott', cn: '斯科特' },
  { en: 'Price', cn: '普赖斯' }, { en: 'Miles', cn: '迈尔斯' }, { en: 'Cole', cn: '科尔' },
  { en: 'Young', cn: '扬' }, { en: 'Ford', cn: '福特' }, { en: 'Reed', cn: '里德' },
  { en: 'Simmons', cn: '西蒙斯' }, { en: 'White', cn: '怀特' }, { en: 'Green', cn: '格林' },
  { en: 'Fox', cn: '福克斯' }, { en: 'Page', cn: '佩奇' }, { en: 'Cross', cn: '克罗斯' },
  { en: 'Lane', cn: '莱恩' }, { en: 'Moore', cn: '摩尔' }, { en: 'Wade', cn: '韦德' },
  { en: 'Stone', cn: '斯通' }, { en: 'Bass', cn: '巴斯' }, { en: 'Hall', cn: '霍尔' },
  { en: 'Bell', cn: '贝尔' }, { en: 'Hart', cn: '哈特' }, { en: 'Hayes', cn: '海斯' },
  { en: 'Holt', cn: '霍尔特' }, { en: 'Kane', cn: '凯恩' }, { en: 'Knox', cn: '诺克斯' },
  { en: 'Lloyd', cn: '劳埃德' }, { en: 'Mason', cn: '梅森' }, { en: 'Nixon', cn: '尼克松' },
  { en: 'Ortiz', cn: '奥尔蒂斯' }, { en: 'Payne', cn: '佩恩' }, { en: 'Quinn', cn: '奎因' },
  { en: 'Rose', cn: '罗斯' }, { en: 'Shaw', cn: '肖' }, { en: 'Tucker', cn: '塔克' },
  { en: 'Vance', cn: '万斯' }, { en: 'Ward', cn: '沃德' }, { en: 'Yates', cn: '耶茨' },
  { en: 'Abbott', cn: '阿博特' }, { en: 'Bishop', cn: '毕晓普' }, { en: 'Clayton', cn: '克莱顿' },
  { en: 'Doyle', cn: '多伊尔' }, { en: 'Ellis', cn: '埃利斯' }, { en: 'Fletcher', cn: '弗莱彻' },
  { en: 'Graves', cn: '格雷夫斯' }, { en: 'Henson', cn: '亨森' }, { en: 'Ingram', cn: '英格拉姆' },
  { en: 'Jensen', cn: '詹森' }, { en: 'Keller', cn: '凯勒' }, { en: 'Lynch', cn: '林奇' },
  { en: 'Mercer', cn: '默瑟' }, { en: 'Norton', cn: '诺顿' }, { en: 'Odom', cn: '奥多姆' },
  { en: 'Porter', cn: '波特' }, { en: 'Ramsey', cn: '拉姆齐' }, { en: 'Trent', cn: '特伦特' },
];

